import type { GeoLocation } from "./types.ts";

const V = "2026-09-21";

function loc(
  partial: Omit<GeoLocation, "verifiedAt" | "enabled" | "sceneUrl"> & {
    sceneKind: GeoLocation["sceneKind"];
    sceneUrl?: string;
  },
): GeoLocation {
  return {
    ...partial,
    verifiedAt: V,
    enabled: true,
    sceneUrl: partial.sceneUrl ?? `/locations/${partial.id}.jpg`,
  };
}

/** 15 extra ZA + 15 extra NL photo sites. Coordinates from Wikipedia 2026-09-21. */
export const EXTRA_LOCATIONS: GeoLocation[] = [
  loc({
    id: "loc_41",
    country: "ZA",
    title: "Robben Island",
    city: "Cape Town",
    region: "Western Cape",
    latitude: -33.805,
    longitude: 18.37,
    difficulty: 2,
    tags: ["island", "historic", "coastal", "iconic"],
    attribution: "Photo: Wikimedia Commons, CC BY-SA. Wikipedia: Robben Island.",
    sourceUrl: "https://en.wikipedia.org/wiki/Robben_Island",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_42",
    country: "ZA",
    title: "Boulders Beach",
    city: "Simon’s Town",
    region: "Western Cape",
    latitude: -34.197,
    longitude: 18.451,
    difficulty: 3,
    tags: ["coastal", "beach", "wildlife"],
    attribution: "Cinematic reconstruction inspired by Boulders Beach. Not a live street photograph. Coordinates from Wikipedia.",
    sourceUrl: "https://en.wikipedia.org/wiki/Boulders_Beach",
    sceneKind: "wikimedia",
      }),
  loc({
    id: "loc_43",
    country: "ZA",
    title: "Chapman’s Peak",
    city: "Hout Bay",
    region: "Western Cape",
    latitude: -34.08722,
    longitude: 18.36056,
    difficulty: 3,
    tags: ["coastal", "mountain", "road"],
    attribution: "Cinematic reconstruction inspired by Chapman’s Peak. Not a live street photograph. Coordinates from Wikipedia.",
    sourceUrl: "https://en.wikipedia.org/wiki/Chapman%27s_Peak",
    sceneKind: "wikimedia",
      }),
  loc({
    id: "loc_44",
    country: "ZA",
    title: "Hermanus Old Harbour",
    city: "Hermanus",
    region: "Western Cape",
    latitude: -34.4186,
    longitude: 19.2444,
    difficulty: 3,
    tags: ["coastal", "harbor", "town"],
    attribution: "Photo: Wikimedia Commons, CC BY-SA. Wikipedia: Hermanus.",
    sourceUrl: "https://en.wikipedia.org/wiki/Hermanus",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_45",
    country: "ZA",
    title: "Franschhoek",
    city: "Franschhoek",
    region: "Western Cape",
    latitude: -33.9072,
    longitude: 19.1175,
    difficulty: 3,
    tags: ["valley", "vineyard", "town"],
    attribution: "Photo: Wikimedia Commons, CC BY-SA. Wikipedia: Franschhoek.",
    sourceUrl: "https://en.wikipedia.org/wiki/Franschhoek",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_46",
    country: "ZA",
    title: "Storms River Mouth",
    city: "Tsitsikamma",
    region: "Eastern Cape",
    latitude: -33.972,
    longitude: 23.6414,
    difficulty: 4,
    tags: ["coastal", "forest", "park"],
    attribution: "Photo: Wikimedia Commons, CC BY-SA. Wikipedia: Tsitsikamma National Park.",
    sourceUrl: "https://en.wikipedia.org/wiki/Tsitsikamma_National_Park",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_47",
    country: "ZA",
    title: "Addo Elephant Park",
    city: "Addo",
    region: "Eastern Cape",
    latitude: -33.44611,
    longitude: 25.74583,
    difficulty: 4,
    tags: ["wildlife", "park", "landscape"],
    attribution: "Photo: Wikimedia Commons, CC BY-SA. Wikipedia: Addo Elephant National Park.",
    sourceUrl: "https://en.wikipedia.org/wiki/Addo_Elephant_National_Park",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_48",
    country: "ZA",
    title: "Moses Mabhida Stadium",
    city: "Durban",
    region: "KwaZulu-Natal",
    latitude: -29.8289,
    longitude: 31.0303,
    difficulty: 2,
    tags: ["stadium", "urban", "iconic"],
    attribution: "Cinematic reconstruction inspired by Moses Mabhida Stadium. Not a live street photograph. Coordinates from Wikipedia.",
    sourceUrl: "https://en.wikipedia.org/wiki/Moses_Mabhida_Stadium",
    sceneKind: "wikimedia",
      }),
  loc({
    id: "loc_49",
    country: "ZA",
    title: "Pietermaritzburg City Hall",
    city: "Pietermaritzburg",
    region: "KwaZulu-Natal",
    latitude: -29.6014,
    longitude: 30.3794,
    difficulty: 3,
    tags: ["civic", "architecture", "urban"],
    attribution: "Cinematic reconstruction inspired by Pietermaritzburg. Not a live street photograph. Coordinates from Wikipedia.",
    sourceUrl: "https://en.wikipedia.org/wiki/Pietermaritzburg",
    sceneKind: "wikimedia",
      }),
  loc({
    id: "loc_50",
    country: "ZA",
    title: "Howick Falls",
    city: "Howick",
    region: "KwaZulu-Natal",
    latitude: -29.4867,
    longitude: 30.2386,
    difficulty: 3,
    tags: ["waterfall", "landscape"],
    attribution: "Photo: Wikimedia Commons, CC BY-SA. Wikipedia: Howick Falls.",
    sourceUrl: "https://en.wikipedia.org/wiki/Howick_Falls",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_51",
    country: "ZA",
    title: "Hillbrow Tower",
    city: "Johannesburg",
    region: "Gauteng",
    latitude: -26.1869,
    longitude: 28.0492,
    difficulty: 2,
    tags: ["tower", "urban", "skyline", "iconic"],
    attribution: "Cinematic reconstruction inspired by Hillbrow Tower. Not a live street photograph. Coordinates from Wikipedia.",
    sourceUrl: "https://en.wikipedia.org/wiki/Hillbrow_Tower",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_52",
    country: "ZA",
    title: "Voortrekker Monument",
    city: "Pretoria",
    region: "Gauteng",
    latitude: -25.77639,
    longitude: 28.1775,
    difficulty: 2,
    tags: ["monument", "historic", "architecture"],
    attribution: "Cinematic reconstruction inspired by Voortrekker Monument. Not a live street photograph. Coordinates from Wikipedia.",
    sourceUrl: "https://en.wikipedia.org/wiki/Voortrekker_Monument",
    sceneKind: "wikimedia",
      }),
  loc({
    id: "loc_53",
    country: "ZA",
    title: "Vilakazi Street",
    city: "Soweto",
    region: "Gauteng",
    latitude: -26.2375,
    longitude: 27.9086,
    difficulty: 4,
    tags: ["urban", "historic", "street"],
    attribution: "Cinematic reconstruction inspired by Vilakazi Street. Not a live street photograph. Coordinates from Wikipedia.",
    sourceUrl: "https://en.wikipedia.org/wiki/Orlando,_Soweto",
    sceneKind: "wikimedia",
      }),
  loc({
    id: "loc_54",
    country: "ZA",
    title: "God’s Window",
    city: "Graskop",
    region: "Mpumalanga",
    latitude: -24.8753,
    longitude: 30.892,
    difficulty: 3,
    tags: ["canyon", "escarpment", "landscape"],
    attribution: "Cinematic reconstruction inspired by Blyde River Canyon. Not a live street photograph. Coordinates from Wikipedia.",
    sourceUrl: "https://en.wikipedia.org/wiki/Blyde_River_Canyon",
    sceneKind: "wikimedia",
      }),
  loc({
    id: "loc_55",
    country: "ZA",
    title: "Augrabies Falls",
    city: "Augrabies",
    region: "Northern Cape",
    latitude: -28.59139,
    longitude: 20.34083,
    difficulty: 4,
    tags: ["waterfall", "desert", "landscape"],
    attribution: "Photo: Wikimedia Commons, CC BY-SA. Wikipedia: Augrabies Falls.",
    sourceUrl: "https://en.wikipedia.org/wiki/Augrabies_Falls",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_56",
    country: "NL",
    title: "Rijksmuseum",
    city: "Amsterdam",
    region: "North Holland",
    latitude: 52.36,
    longitude: 4.8853,
    difficulty: 2,
    tags: ["museum", "architecture", "urban", "iconic"],
    attribution: "Cinematic reconstruction inspired by Rijksmuseum. Not a live street photograph. Coordinates from Wikipedia.",
    sourceUrl: "https://en.wikipedia.org/wiki/Rijksmuseum",
    sceneKind: "wikimedia",
      }),
  loc({
    id: "loc_57",
    country: "NL",
    title: "Magere Brug",
    city: "Amsterdam",
    region: "North Holland",
    latitude: 52.36361,
    longitude: 4.9025,
    difficulty: 3,
    tags: ["bridge", "canal", "urban"],
    attribution: "Cinematic reconstruction inspired by Magere Brug. Not a live street photograph. Coordinates from Wikipedia.",
    sourceUrl: "https://en.wikipedia.org/wiki/Magere_Brug",
    sceneKind: "wikimedia",
      }),
  loc({
    id: "loc_58",
    country: "NL",
    title: "Alkmaar Waag",
    city: "Alkmaar",
    region: "North Holland",
    latitude: 52.6317,
    longitude: 4.7503,
    difficulty: 3,
    tags: ["historic", "market", "urban"],
    attribution: "Cinematic reconstruction inspired by Alkmaar. Not a live street photograph. Coordinates from Wikipedia.",
    sourceUrl: "https://en.wikipedia.org/wiki/Alkmaar",
    sceneKind: "wikimedia",
      }),
  loc({
    id: "loc_59",
    country: "NL",
    title: "Volendam Harbor",
    city: "Volendam",
    region: "North Holland",
    latitude: 52.49944,
    longitude: 5.0675,
    difficulty: 3,
    tags: ["harbor", "village", "coastal"],
    attribution: "Cinematic reconstruction inspired by Volendam. Not a live street photograph. Coordinates from Wikipedia.",
    sourceUrl: "https://en.wikipedia.org/wiki/Volendam",
    sceneKind: "wikimedia",
      }),
  loc({
    id: "loc_60",
    country: "NL",
    title: "Madurodam",
    city: "The Hague",
    region: "South Holland",
    latitude: 52.0995,
    longitude: 4.2975,
    difficulty: 3,
    tags: ["park", "urban", "tourism"],
    attribution: "Photo: Wikimedia Commons, CC BY-SA. Wikipedia: Madurodam.",
    sourceUrl: "https://en.wikipedia.org/wiki/Madurodam",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_61",
    country: "NL",
    title: "Gouda Markt",
    city: "Gouda",
    region: "South Holland",
    latitude: 52.01111,
    longitude: 4.71111,
    difficulty: 3,
    tags: ["market", "historic", "urban"],
    attribution: "Cinematic reconstruction inspired by Gouda, South Holland. Not a live street photograph. Coordinates from Wikipedia.",
    sourceUrl: "https://en.wikipedia.org/wiki/Gouda,_South_Holland",
    sceneKind: "wikimedia",
      }),
  loc({
    id: "loc_62",
    country: "NL",
    title: "Grote Kerk, Breda",
    city: "Breda",
    region: "North Brabant",
    latitude: 51.589,
    longitude: 4.775,
    difficulty: 3,
    tags: ["church", "historic", "urban"],
    attribution: "Cinematic reconstruction inspired by Grote Kerk (Breda). Not a live street photograph. Coordinates from Wikipedia.",
    sourceUrl: "https://en.wikipedia.org/wiki/Grote_Kerk_(Breda)",
    sceneKind: "wikimedia",
      }),
  loc({
    id: "loc_63",
    country: "NL",
    title: "St. John’s Cathedral",
    city: "’s-Hertogenbosch",
    region: "North Brabant",
    latitude: 51.6881,
    longitude: 5.3042,
    difficulty: 3,
    tags: ["cathedral", "historic", "urban"],
    attribution: "Photo: Wikimedia Commons, CC BY-SA. Wikipedia: St. John’s Cathedral (’s-Hertogenbosch).",
    sourceUrl: "https://en.wikipedia.org/wiki/St._John%27s_Cathedral_(%27s-Hertogenbosch)",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_64",
    country: "NL",
    title: "John Frost Bridge",
    city: "Arnhem",
    region: "Gelderland",
    latitude: 51.9747,
    longitude: 5.9114,
    difficulty: 3,
    tags: ["bridge", "river", "urban"],
    attribution: "Cinematic reconstruction inspired by John Frost Bridge. Not a live street photograph. Coordinates from Wikipedia.",
    sourceUrl: "https://en.wikipedia.org/wiki/John_Frost_Bridge",
    sceneKind: "wikimedia",
      }),
  loc({
    id: "loc_65",
    country: "NL",
    title: "Koppelpoort",
    city: "Amersfoort",
    region: "Utrecht",
    latitude: 52.1567,
    longitude: 5.3844,
    difficulty: 3,
    tags: ["gate", "historic", "water"],
    attribution: "Cinematic reconstruction inspired by Koppelpoort. Not a live street photograph. Coordinates from Wikipedia.",
    sourceUrl: "https://en.wikipedia.org/wiki/Koppelpoort",
    sceneKind: "wikimedia",
      }),
  loc({
    id: "loc_66",
    country: "NL",
    title: "Naarden Vesting",
    city: "Naarden",
    region: "North Holland",
    latitude: 52.2953,
    longitude: 5.1622,
    difficulty: 3,
    tags: ["fort", "historic", "star-fort"],
    attribution: "Photo: Wikimedia Commons, CC BY-SA. Wikipedia: Naarden.",
    sourceUrl: "https://en.wikipedia.org/wiki/Naarden",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_67",
    country: "NL",
    title: "Muiderslot",
    city: "Muiden",
    region: "North Holland",
    latitude: 52.3344,
    longitude: 5.0717,
    difficulty: 3,
    tags: ["castle", "historic", "water"],
    attribution: "Cinematic reconstruction inspired by Muiderslot. Not a live street photograph. Coordinates from Wikipedia.",
    sourceUrl: "https://en.wikipedia.org/wiki/Muiderslot",
    sceneKind: "wikimedia",
      }),
  loc({
    id: "loc_68",
    country: "NL",
    title: "Oldehove",
    city: "Leeuwarden",
    region: "Friesland",
    latitude: 53.2029,
    longitude: 5.7926,
    difficulty: 3,
    tags: ["tower", "historic", "urban"],
    attribution: "Cinematic reconstruction inspired by Oldehove. Not a live street photograph. Coordinates from Wikipedia.",
    sourceUrl: "https://en.wikipedia.org/wiki/Oldehove_(Leeuwarden)",
    sceneKind: "wikimedia",
      }),
  loc({
    id: "loc_69",
    country: "NL",
    title: "Lange Jan",
    city: "Middelburg",
    region: "Zeeland",
    latitude: 51.4997,
    longitude: 3.6144,
    difficulty: 4,
    tags: ["tower", "abbey", "historic"],
    attribution: "Photo: Wikimedia Commons, CC BY-SA. Wikipedia: Middelburg, Zeeland.",
    sourceUrl: "https://en.wikipedia.org/wiki/Middelburg,_Zeeland",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_70",
    country: "NL",
    title: "Grote Kerk, Dordrecht",
    city: "Dordrecht",
    region: "South Holland",
    latitude: 51.8136,
    longitude: 4.6697,
    difficulty: 3,
    tags: ["church", "historic", "urban"],
    attribution: "Photo: Wikimedia Commons, CC BY-SA. Wikipedia: Grote Kerk, Dordrecht.",
    sourceUrl: "https://en.wikipedia.org/wiki/Grote_Kerk_(Dordrecht)",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
];
