// Generated by scripts/build-hires-manifest.mjs — do not edit by hand.
// Run `node scripts/build-hires-manifest.mjs` after adding a plate to
// public/locations/hires/.

/** Pixel widths of the plates that ship a larger companion under hires/. */
export const HIRES_PLATES: Record<string, { base: number; hires: number }> = {
  "loc_02": { base: 1280, hires: 5844 },
};
