import { EXTRA_LOCATIONS } from "./extra-locations.ts";
import { PACK_LOCATIONS } from "./pack-locations.ts";
import type { GeoLocation } from "./types.ts";

const V = "2026-09-20";

function loc(
  partial: Omit<GeoLocation, "verifiedAt" | "enabled" | "sceneUrl"> & {
    sceneKind: GeoLocation["sceneKind"];
    sceneUrl?: string;
  },
): GeoLocation {
  return {
    ...partial,
    verifiedAt: V,
    enabled: true,
    sceneUrl: partial.sceneUrl ?? `/locations/${partial.id}.jpg`,
  };
}

/**
 * Launch pool: 30 South Africa + 30 Netherlands photos.
 * Coordinates cross-checked against Wikipedia/Wikimedia 2026-09-20
 * and conservative national bounding boxes (see validation.ts).
 */
export const LAUNCH_LOCATIONS: GeoLocation[] = [
  loc({
    id: "loc_01",
    country: "ZA",
    title: "Table Mountain",
    city: "Cape Town",
    region: "Western Cape",
    latitude: -33.96218,
    longitude: 18.409883,
    difficulty: 2,
    tags: ["mountain", "coastal", "iconic", "landscape"],
    attribution:
      "360° plate: Greg Zaal and Rico Cilliers, Poly Haven, CC0. Still: DanieVDM, Wikimedia Commons, CC BY-SA. Wikipedia: Table Mountain.",
    sourceUrl: "https://en.wikipedia.org/wiki/Table_Mountain",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
    panoUrl: "/locations/pano_table_mountain.jpg",
    pitch: -20,
  }),
  loc({
    id: "loc_02",
    country: "ZA",
    title: "V&A Waterfront",
    city: "Cape Town",
    region: "Western Cape",
    latitude: -33.903056,
    longitude: 18.422778,
    difficulty: 3,
    tags: ["harbor", "urban", "coastal", "tourism"],
    attribution: "Photo: Wikimedia Commons contributors, CC BY-SA. Wikipedia: V&A Waterfront.",
    sourceUrl: "https://en.wikipedia.org/wiki/V%26A_Waterfront",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_03",
    country: "ZA",
    title: "Sandton City",
    city: "Sandton",
    region: "Gauteng",
    latitude: -26.108333,
    longitude: 28.054167,
    difficulty: 3,
    tags: ["urban", "modern", "cbd", "skyline"],
    attribution: "Photo: Wikimedia Commons contributors, CC BY-SA. Wikipedia: Sandton City.",
    sourceUrl: "https://en.wikipedia.org/wiki/Sandton_City",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_04",
    country: "ZA",
    title: "Union Buildings",
    city: "Pretoria",
    region: "Gauteng",
    latitude: -25.740467,
    longitude: 28.212022,
    difficulty: 2,
    tags: ["civic", "historic", "architecture", "urban"],
    attribution: "Photo: Wikimedia Commons contributors, CC BY-SA. Wikipedia: Union Buildings.",
    sourceUrl: "https://en.wikipedia.org/wiki/Union_Buildings",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_05",
    country: "ZA",
    title: "North Beach",
    city: "Durban",
    region: "KwaZulu-Natal",
    latitude: -29.8587,
    longitude: 31.0218,
    difficulty: 3,
    tags: ["coastal", "urban", "promenade", "beach"],
    attribution:
      "Photo: Wikimedia Commons, CC BY-SA. Wikipedia: North Beach, Durban.",
    sourceUrl: "https://en.wikipedia.org/wiki/North_Beach,_Durban",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_06",
    country: "ZA",
    title: "Stellenbosch",
    city: "Stellenbosch",
    region: "Western Cape",
    latitude: -33.936667,
    longitude: 18.861389,
    difficulty: 3,
    tags: ["vineyard", "historic", "rural", "mountain"],
    attribution: "Photo: lumoplank, Wikimedia Commons, CC0. Wikipedia: Stellenbosch.",
    sourceUrl: "https://en.wikipedia.org/wiki/Stellenbosch",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_07",
    country: "ZA",
    title: "Bloemfontein",
    city: "Bloemfontein",
    region: "Free State",
    latitude: -29.116667,
    longitude: 26.216667,
    difficulty: 4,
    tags: ["urban", "highveld", "civic"],
    attribution: "Photo: Diether, Wikimedia Commons, CC BY-SA 4.0. Wikipedia: Bloemfontein.",
    sourceUrl: "https://en.wikipedia.org/wiki/Bloemfontein",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_08",
    country: "ZA",
    title: "The Big Hole",
    city: "Kimberley",
    region: "Northern Cape",
    latitude: -28.738889,
    longitude: 24.758889,
    difficulty: 2,
    tags: ["mine", "infrastructure", "iconic", "landscape"],
    attribution: "Photo: Wikimedia Commons contributors, CC BY-SA. Wikipedia: Big Hole.",
    sourceUrl: "https://en.wikipedia.org/wiki/Big_Hole",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_09",
    country: "ZA",
    title: "Mbombela",
    city: "Mbombela",
    region: "Mpumalanga",
    latitude: -25.465833,
    longitude: 30.985278,
    difficulty: 4,
    tags: ["urban", "lowveld", "landscape"],
    attribution: "Photo: Werner Bayer, Wikimedia Commons, CC0. Wikipedia: Mbombela.",
    sourceUrl: "https://en.wikipedia.org/wiki/Mbombela",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_10",
    country: "ZA",
    title: "Polokwane",
    city: "Polokwane",
    region: "Limpopo",
    latitude: -23.9,
    longitude: 29.45,
    difficulty: 5,
    tags: ["urban", "suburban", "inland"],
    attribution: "Photo: JasonMoe289, Wikimedia Commons, CC BY-SA 4.0. Wikipedia: Polokwane.",
    sourceUrl: "https://en.wikipedia.org/wiki/Polokwane",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_11",
    country: "ZA",
    title: "Cape Point",
    city: "Cape Town",
    region: "Western Cape",
    latitude: -34.357222,
    longitude: 18.4975,
    difficulty: 2,
    tags: ["coastal", "mountain", "landscape", "iconic"],
    attribution: "Photo: Wikimedia Commons contributors, CC BY-SA. Wikipedia: Cape Point.",
    sourceUrl: "https://en.wikipedia.org/wiki/Cape_Point",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_12",
    country: "ZA",
    title: "Orlando Towers",
    city: "Soweto",
    region: "Gauteng",
    latitude: -26.253889,
    longitude: 27.925,
    difficulty: 3,
    tags: ["infrastructure", "urban", "iconic"],
    attribution: "Photo: Pierre Andre Leclercq, Wikimedia Commons, CC BY-SA 3.0. Wikipedia: Orlando Power Station.",
    sourceUrl: "https://en.wikipedia.org/wiki/Orlando_Power_Station",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_13",
    country: "ZA",
    title: "Knysna Waterfront",
    city: "Knysna",
    region: "Western Cape",
    latitude: -34.035556,
    longitude: 23.048889,
    difficulty: 3,
    tags: ["coastal", "harbor", "garden-route"],
    attribution: "Photo: Ad Meskens, Wikimedia Commons, CC BY-SA 4.0. Wikipedia: Knysna.",
    sourceUrl: "https://en.wikipedia.org/wiki/Knysna",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_14",
    country: "ZA",
    title: "Drakensberg Amphitheatre",
    city: "Royal Natal",
    region: "KwaZulu-Natal",
    latitude: -28.7519,
    longitude: 28.8958,
    difficulty: 2,
    tags: ["mountain", "landscape", "rural"],
    attribution: "Photo: PhilippN, Wikimedia Commons, CC BY-SA 3.0. Wikipedia: Royal Natal National Park.",
    sourceUrl: "https://en.wikipedia.org/wiki/Royal_Natal_National_Park",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_15",
    country: "ZA",
    title: "Donkin Reserve",
    city: "Gqeberha",
    region: "Eastern Cape",
    latitude: -33.9608,
    longitude: 25.6197,
    difficulty: 4,
    tags: ["coastal", "civic", "historic", "urban"],
    attribution:
      "Photo: Wikimedia Commons, CC BY-SA. Wikipedia: Gqeberha.",
    sourceUrl: "https://en.wikipedia.org/wiki/Gqeberha",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_16",
    country: "NL",
    title: "Dam Square",
    city: "Amsterdam",
    region: "North Holland",
    latitude: 52.3731,
    longitude: 4.8928,
    difficulty: 1,
    tags: ["urban", "historic", "plaza", "iconic"],
    attribution: "Photo: C messier, Wikimedia Commons, CC BY-SA 4.0. Wikipedia: Dam Square.",
    sourceUrl: "https://en.wikipedia.org/wiki/Dam_Square",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_17",
    country: "NL",
    title: "Erasmusbrug",
    city: "Rotterdam",
    region: "South Holland",
    latitude: 51.909167,
    longitude: 4.486667,
    difficulty: 2,
    tags: ["harbor", "modern", "infrastructure", "iconic"],
    attribution: "Photo: Wikimedia Commons contributors, CC BY-SA. Wikipedia: Erasmusbrug.",
    sourceUrl: "https://en.wikipedia.org/wiki/Erasmusbrug",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_18",
    country: "NL",
    title: "Binnenhof",
    city: "The Hague",
    region: "South Holland",
    latitude: 52.079631,
    longitude: 4.313035,
    difficulty: 2,
    tags: ["civic", "historic", "urban", "architecture"],
    attribution: "Photo: Hubertl, Wikimedia Commons, CC BY-SA 4.0. Wikipedia: Binnenhof.",
    sourceUrl: "https://en.wikipedia.org/wiki/Binnenhof",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_19",
    country: "NL",
    title: "Dom Tower",
    city: "Utrecht",
    region: "Utrecht",
    latitude: 52.09065,
    longitude: 5.1214,
    difficulty: 2,
    tags: ["historic", "urban", "architecture", "iconic"],
    attribution: "Photo: C messier, Wikimedia Commons, CC BY-SA 4.0. Wikipedia: Dom Tower of Utrecht.",
    sourceUrl: "https://en.wikipedia.org/wiki/Dom_Tower_of_Utrecht",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_20",
    country: "NL",
    title: "Lichttoren, Strijp-S",
    city: "Eindhoven",
    region: "North Brabant",
    latitude: 51.4474,
    longitude: 5.4563,
    difficulty: 4,
    tags: ["modern", "industrial", "urban", "infrastructure"],
    attribution:
      "Photo: Wikimedia Commons, CC BY-SA. Wikipedia: Eindhoven.",
    sourceUrl: "https://en.wikipedia.org/wiki/Eindhoven",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_21",
    country: "NL",
    title: "Grote Markt, Groningen",
    city: "Groningen",
    region: "Groningen",
    latitude: 53.2186,
    longitude: 6.5676,
    difficulty: 3,
    tags: ["historic", "plaza", "urban"],
    attribution:
      "Photo: Wikimedia Commons, CC BY-SA. Wikipedia: Grote Markt (Groningen).",
    sourceUrl: "https://en.wikipedia.org/wiki/Grote_Markt_(Groningen)",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_22",
    country: "NL",
    title: "Vrijthof",
    city: "Maastricht",
    region: "Limburg",
    latitude: 50.849172,
    longitude: 5.688419,
    difficulty: 3,
    tags: ["historic", "plaza", "urban", "architecture"],
    attribution: "Photo: Berthold Werner, Wikimedia Commons, CC BY-SA 4.0. Wikipedia: Vrijthof.",
    sourceUrl: "https://en.wikipedia.org/wiki/Vrijthof",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_23",
    country: "NL",
    title: "Delft historic centre",
    city: "Delft",
    region: "South Holland",
    latitude: 52.011667,
    longitude: 4.359167,
    difficulty: 3,
    tags: ["historic", "canal", "urban", "architecture"],
    attribution: "Photo: Ralf Roletschek, Wikimedia Commons, GFDL 1.2. Wikipedia: Delft.",
    sourceUrl: "https://en.wikipedia.org/wiki/Delft",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_24",
    country: "NL",
    title: "Grote Markt, Haarlem",
    city: "Haarlem",
    region: "North Holland",
    latitude: 52.381367,
    longitude: 4.635906,
    difficulty: 3,
    tags: ["historic", "plaza", "urban"],
    attribution: "Photo: Wolfgang Moroder, Wikimedia Commons, CC BY-SA 4.0. Wikipedia: Grote Markt (Haarlem).",
    sourceUrl: "https://en.wikipedia.org/wiki/Grote_Markt_(Haarlem)",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_25",
    country: "NL",
    title: "Hortus Botanicus",
    city: "Leiden",
    region: "South Holland",
    latitude: 52.157094,
    longitude: 4.484522,
    difficulty: 3,
    tags: ["canal", "historic", "garden", "urban"],
    attribution: "Photo: Tubantia, Wikimedia Commons, CC BY-SA 3.0. Wikipedia: Hortus Botanicus Leiden.",
    sourceUrl: "https://en.wikipedia.org/wiki/Hortus_Botanicus_Leiden",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_26",
    country: "NL",
    title: "Zaanse Schans",
    city: "Zaanstad",
    region: "North Holland",
    latitude: 52.473889,
    longitude: 4.816389,
    difficulty: 2,
    tags: ["rural", "windmill", "historic", "polder"],
    attribution: "Photo: DimiTalen, Wikimedia Commons, CC0. Wikipedia: Zaanse Schans.",
    sourceUrl: "https://en.wikipedia.org/wiki/Zaanse_Schans",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_27",
    country: "NL",
    title: "Kinderdijk windmills",
    city: "Kinderdijk",
    region: "South Holland",
    latitude: 51.8825,
    longitude: 4.649444,
    difficulty: 1,
    tags: ["rural", "windmill", "polder", "iconic"],
    attribution: "Photo: John Samuel, Wikimedia Commons, CC BY-SA 4.0. Wikipedia: Kinderdijk windmills.",
    sourceUrl: "https://en.wikipedia.org/wiki/Kinderdijk_windmills",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_28",
    country: "NL",
    title: "Giethoorn",
    city: "Giethoorn",
    region: "Overijssel",
    latitude: 52.738889,
    longitude: 6.078056,
    difficulty: 2,
    tags: ["canal", "rural", "village"],
    attribution: "Photo: Steven Lek, Wikimedia Commons, CC BY-SA 4.0. Wikipedia: Giethoorn.",
    sourceUrl: "https://en.wikipedia.org/wiki/Giethoorn",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  loc({
    id: "loc_29",
    country: "NL",
    title: "Scheveningen Pier",
    city: "The Hague",
    region: "South Holland",
    latitude: 52.117222,
    longitude: 4.28,
    difficulty: 3,
    tags: ["coastal", "beach", "infrastructure"],
    attribution:
      "360° plate: Wvdp, Wikimedia Commons, CC0. Still: Michielverbeek, Wikimedia Commons, CC BY-SA 4.0. Wikipedia: Scheveningen Pier.",
    sourceUrl: "https://en.wikipedia.org/wiki/Scheveningen_Pier",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
    panoUrl: "/locations/pano_scheveningen.jpg",
    pitch: -20,
  }),
  loc({
    id: "loc_30",
    country: "NL",
    title: "Cube Houses",
    city: "Rotterdam",
    region: "South Holland",
    latitude: 51.920278,
    longitude: 4.490556,
    difficulty: 2,
    tags: ["modern", "architecture", "urban", "iconic"],
    attribution: "Photo: W. Bulach, Wikimedia Commons, CC BY-SA 4.0. Wikipedia: Cube house.",
    sourceUrl: "https://en.wikipedia.org/wiki/Cube_house",
    sceneKind: "wikimedia",
    panoramaProvider: "wikimedia",
  }),
  ...EXTRA_LOCATIONS,
];

/** Ten reconstruction sites reserved for round 4. 3D renderer is parked (OpenCode / GPT-6 Astra). Do not delete. */
export const ROUND4_LOCATIONS: GeoLocation[] = [
  loc({
    id: "loc_31",
    country: "ZA",
    title: "Three Rondavels",
    city: "Blyde River Canyon",
    region: "Mpumalanga",
    latitude: -24.5734,
    longitude: 30.8078,
    difficulty: 3,
    tags: ["canyon", "mountain", "iconic", "landscape"],
    attribution: "3D reconstruction. Coordinates: Wikipedia, Three Rondavels.",
    sourceUrl: "https://en.wikipedia.org/wiki/Three_Rondavels",
    sceneKind: "generated-reconstruction",
    sceneUrl: "/generated/round4-cape.jpg",
  }),
  loc({
    id: "loc_32",
    country: "ZA",
    title: "Cape Agulhas Lighthouse",
    city: "L'Agulhas",
    region: "Western Cape",
    latitude: -34.82972,
    longitude: 20.00889,
    difficulty: 3,
    tags: ["coastal", "lighthouse", "iconic"],
    attribution: "3D reconstruction. Coordinates: Wikipedia, Cape Agulhas Lighthouse.",
    sourceUrl: "https://en.wikipedia.org/wiki/Cape_Agulhas_Lighthouse",
    sceneKind: "generated-reconstruction",
    sceneUrl: "/generated/home-cape.jpg",
  }),
  loc({
    id: "loc_33",
    country: "ZA",
    title: "Kirstenbosch",
    city: "Cape Town",
    region: "Western Cape",
    latitude: -33.9875,
    longitude: 18.4325,
    difficulty: 3,
    tags: ["garden", "mountain", "botanical"],
    attribution: "3D reconstruction. Coordinates: Wikipedia, Kirstenbosch National Botanical Garden.",
    sourceUrl: "https://en.wikipedia.org/wiki/Kirstenbosch_National_Botanical_Garden",
    sceneKind: "generated-reconstruction",
    sceneUrl: "/generated/home-cape.jpg",
  }),
  loc({
    id: "loc_34",
    country: "ZA",
    title: "Hartbeespoort Dam",
    city: "Hartbeespoort",
    region: "North West",
    latitude: -25.7478,
    longitude: 27.8531,
    difficulty: 4,
    tags: ["dam", "valley", "recreation"],
    attribution: "3D reconstruction. Coordinates: Wikipedia, Hartbeespoort Dam.",
    sourceUrl: "https://en.wikipedia.org/wiki/Hartbeespoort_Dam",
    sceneKind: "generated-reconstruction",
    sceneUrl: "/generated/home-johannesburg.jpg",
  }),
  loc({
    id: "loc_35",
    country: "ZA",
    title: "Cango Caves",
    city: "Oudtshoorn",
    region: "Western Cape",
    latitude: -33.3928,
    longitude: 22.2147,
    difficulty: 4,
    tags: ["cave", "karoo", "landscape"],
    attribution: "3D reconstruction. Coordinates: Wikipedia, Cango Caves.",
    sourceUrl: "https://en.wikipedia.org/wiki/Cango_Caves",
    sceneKind: "generated-reconstruction",
    sceneUrl: "/generated/home-cape.jpg",
  }),
  loc({
    id: "loc_36",
    country: "NL",
    title: "Keukenhof",
    city: "Lisse",
    region: "South Holland",
    latitude: 52.2714,
    longitude: 4.5464,
    difficulty: 3,
    tags: ["garden", "rural", "iconic"],
    attribution: "3D reconstruction. Coordinates: Wikipedia, Keukenhof.",
    sourceUrl: "https://en.wikipedia.org/wiki/Keukenhof",
    sceneKind: "generated-reconstruction",
    sceneUrl: "/generated/home-amsterdam.jpg",
  }),
  loc({
    id: "loc_37",
    country: "NL",
    title: "Neeltje Jans",
    city: "Oosterschelde",
    region: "Zeeland",
    latitude: 51.6236,
    longitude: 3.7033,
    difficulty: 4,
    tags: ["coastal", "infrastructure", "delta"],
    attribution: "3D reconstruction. Coordinates: Wikipedia, Neeltje Jans.",
    sourceUrl: "https://en.wikipedia.org/wiki/Neeltje_Jans",
    sceneKind: "generated-reconstruction",
    sceneUrl: "/generated/home-rotterdam.jpg",
  }),
  loc({
    id: "loc_38",
    country: "NL",
    title: "Eierland Lighthouse",
    city: "Texel",
    region: "North Holland",
    latitude: 53.1817,
    longitude: 4.855,
    difficulty: 4,
    tags: ["coastal", "lighthouse", "island"],
    attribution: "3D reconstruction. Coordinates: Wikipedia, Eierland Lighthouse.",
    sourceUrl: "https://en.wikipedia.org/wiki/Eierland_Lighthouse",
    sceneKind: "generated-reconstruction",
    sceneUrl: "/generated/round4-amsterdam.jpg",
  }),
  loc({
    id: "loc_39",
    country: "NL",
    title: "Waalbrug",
    city: "Nijmegen",
    region: "Gelderland",
    latitude: 51.8483,
    longitude: 5.8736,
    difficulty: 3,
    tags: ["bridge", "river", "urban"],
    attribution: "3D reconstruction. Coordinates: Wikipedia, Waalbrug.",
    sourceUrl: "https://en.wikipedia.org/wiki/Waalbrug",
    sceneKind: "generated-reconstruction",
    sceneUrl: "/generated/home-rotterdam.jpg",
  }),
  loc({
    id: "loc_40",
    country: "NL",
    title: "Marken Lighthouse",
    city: "Marken",
    region: "North Holland",
    latitude: 52.4592,
    longitude: 5.1006,
    difficulty: 4,
    tags: ["coastal", "lighthouse", "village"],
    attribution: "3D reconstruction. Coordinates: Wikipedia, Paard van Marken.",
    sourceUrl: "https://en.wikipedia.org/wiki/Paard_van_Marken",
    sceneKind: "generated-reconstruction",
    sceneUrl: "/generated/round4-amsterdam.jpg",
  }),
];

const byId = new Map([...LAUNCH_LOCATIONS, ...ROUND4_LOCATIONS, ...PACK_LOCATIONS].map((l) => [l.id, l]));

export function getLocation(id: string): GeoLocation | undefined {
  return byId.get(id);
}

export function enabledLocations(): GeoLocation[] {
  return [...LAUNCH_LOCATIONS, ...ROUND4_LOCATIONS, ...PACK_LOCATIONS].filter((l) => l.enabled);
}

export function locationCountryLabel(loc: Pick<GeoLocation, "country" | "region" | "nation">): string {
  if (loc.country === "ZA") return "South Africa";
  if (loc.country === "NL") return "Netherlands";
  return loc.region?.trim() || loc.nation || "World";
}
