import type { GeoLocation } from "./types.ts";

const V = "2026-09-21";

function loc(
  partial: Omit<GeoLocation, "verifiedAt" | "enabled" | "sceneUrl"> & {
    sceneUrl?: string;
    enabled?: boolean;
  },
): GeoLocation {
  return {
    ...partial,
    verifiedAt: V,
    enabled: partial.enabled ?? true,
    sceneUrl: partial.sceneUrl ?? `/locations/${partial.id}.jpg`,
  };
}

/** +15 ZA, +15 NL, +49 WORLD → 149-site pool with the existing 70. */
export const PACK_LOCATIONS: GeoLocation[] = [
  loc({
    id: "loc_71",
    country: "ZA",
    title: "Bo-Kaap",
    city: "Cape Town",
    region: "Western Cape",
    latitude: -33.9215,
    longitude: 18.4152,
    difficulty: 3,
    tags: ["urban", "color", "historic"],
    attribution: "Photo: SkyPixels, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Bo-Kaap",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_72",
    country: "ZA",
    title: "Castle of Good Hope",
    city: "Cape Town",
    region: "Western Cape",
    latitude: -33.9258,
    longitude: 18.4278,
    difficulty: 3,
    tags: ["fort", "historic", "urban"],
    attribution: "Photo: Bernard Gagnon, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Castle_of_Good_Hope",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_73",
    country: "ZA",
    title: "Apartheid Museum",
    city: "Johannesburg",
    region: "Gauteng",
    latitude: -26.2366,
    longitude: 28.0092,
    difficulty: 4,
    tags: ["museum", "urban", "historic"],
    attribution: "Photo: Genet, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Apartheid_Museum",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_74",
    country: "ZA",
    title: "FNB Stadium",
    city: "Soweto",
    region: "Gauteng",
    latitude: -26.2348,
    longitude: 27.9826,
    difficulty: 3,
    tags: ["stadium", "urban", "iconic"],
    attribution: "Photo: fading, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/FNB_Stadium",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_75",
    country: "ZA",
    title: "East London City Hall",
    city: "East London",
    region: "Eastern Cape",
    latitude: -33.0153,
    longitude: 27.9116,
    difficulty: 4,
    tags: ["civic", "urban", "coastal"],
    attribution: "Photo: Bfluff, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/East_London,_South_Africa",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_76",
    country: "ZA",
    title: "Upington",
    city: "Upington",
    region: "Northern Cape",
    latitude: -28.4478,
    longitude: 21.2561,
    difficulty: 4,
    tags: ["town", "desert", "river"],
    attribution: "Photo: Col André Kritzinger, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Upington",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_77",
    country: "ZA",
    title: "Langebaan Lagoon",
    city: "Langebaan",
    region: "Western Cape",
    latitude: -33.0919,
    longitude: 18.0311,
    difficulty: 4,
    tags: ["lagoon", "coastal", "west-coast"],
    attribution: "Photo: Winfried Bruenken (Amrum), Wikimedia Commons, CC BY-SA 2.5.",
    sourceUrl: "https://en.wikipedia.org/wiki/Langebaan",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_78",
    country: "ZA",
    title: "Wilderness Beach",
    city: "Wilderness",
    region: "Western Cape",
    latitude: -33.9936,
    longitude: 22.575,
    difficulty: 4,
    tags: ["beach", "coastal", "garden-route"],
    attribution: "Photo: M.Uebel, Wikimedia Commons, Public domain.",
    sourceUrl: "https://en.wikipedia.org/wiki/Wilderness,_Western_Cape",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_79",
    country: "ZA",
    title: "Hluhluwe",
    city: "Hluhluwe",
    region: "KwaZulu-Natal",
    latitude: -28.038,
    longitude: 32.286,
    difficulty: 4,
    tags: ["wildlife", "park", "bush"],
    attribution: "Photo: Neil Strickland, Wikimedia Commons, CC BY 2.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Hluhluwe%E2%80%93Imfolozi_Park",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_80",
    country: "ZA",
    title: "Pilanesberg",
    city: "Pilanesberg",
    region: "North West",
    latitude: -25.241,
    longitude: 27.081,
    difficulty: 4,
    tags: ["wildlife", "crater", "park"],
    attribution: "Photo: Photograph by Mike Peel (www.mikepeel.net)., Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Pilanesberg_National_Park",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_81",
    country: "ZA",
    title: "Clarens",
    city: "Clarens",
    region: "Free State",
    latitude: -28.5147,
    longitude: 28.4192,
    difficulty: 4,
    tags: ["village", "mountain", "art"],
    attribution: "Photo: Jan Giebelmann, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Clarens,_Free_State",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_82",
    country: "ZA",
    title: "Port St Johns",
    city: "Port St Johns",
    region: "Eastern Cape",
    latitude: -31.6286,
    longitude: 29.5369,
    difficulty: 4,
    tags: ["coastal", "wild-coast", "town"],
    attribution: "Photo: South African Tourism from South Africa, Wikimedia Commons, CC BY 2.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Port_St._Johns",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_83",
    country: "ZA",
    title: "Springbok",
    city: "Springbok",
    region: "Northern Cape",
    latitude: -29.6643,
    longitude: 17.8856,
    difficulty: 5,
    tags: ["desert", "namaqualand", "town"],
    attribution: "Photo: Discott (talk), Wikimedia Commons, Public domain.",
    sourceUrl: "https://en.wikipedia.org/wiki/Springbok,_Northern_Cape",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_84",
    country: "ZA",
    title: "Mahikeng",
    city: "Mahikeng",
    region: "North West",
    latitude: -25.86,
    longitude: 25.644,
    difficulty: 4,
    tags: ["town", "historic", "inland"],
    attribution: "Photo: Diverman, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Mahikeng",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_85",
    country: "ZA",
    title: "Saldanha Bay",
    city: "Saldanha",
    region: "Western Cape",
    latitude: -33.0117,
    longitude: 17.9442,
    difficulty: 4,
    tags: ["harbor", "coastal", "industrial"],
    attribution: "Photo: TheDudeFromTheUpperEchelon, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Saldanha_Bay",
    sceneKind: "wikimedia",
  }),

  loc({
    id: "loc_86",
    country: "NL",
    title: "Tilburg",
    city: "Tilburg",
    region: "North Brabant",
    latitude: 51.5555,
    longitude: 5.0913,
    difficulty: 4,
    tags: ["urban", "city", "brabant"],
    attribution: "Photo: Gijs Franken, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Tilburg",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_87",
    country: "NL",
    title: "Zwolle",
    city: "Zwolle",
    region: "Overijssel",
    latitude: 52.5168,
    longitude: 6.083,
    difficulty: 4,
    tags: ["historic", "city", "sassenpoort"],
    attribution: "Photo: Ben Bender, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Zwolle",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_88",
    country: "NL",
    title: "Enschede",
    city: "Enschede",
    region: "Overijssel",
    latitude: 52.2215,
    longitude: 6.8937,
    difficulty: 4,
    tags: ["urban", "city"],
    attribution: "Photo: Michielverbeek, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Enschede",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_89",
    country: "NL",
    title: "Deventer",
    city: "Deventer",
    region: "Overijssel",
    latitude: 52.2516,
    longitude: 6.1639,
    difficulty: 3,
    tags: ["historic", "ijssel", "town"],
    attribution: "Photo: Apdency, Wikimedia Commons, CC0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Deventer",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_90",
    country: "NL",
    title: "Kampen",
    city: "Kampen",
    region: "Overijssel",
    latitude: 52.555,
    longitude: 5.9114,
    difficulty: 4,
    tags: ["hanseatic", "river", "historic"],
    attribution: "Photo: HenkvD, Wikimedia Commons, CC BY-SA 3.0 nl.",
    sourceUrl: "https://en.wikipedia.org/wiki/Kampen,_Overijssel",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_91",
    country: "NL",
    title: "Hoorn",
    city: "Hoorn",
    region: "North Holland",
    latitude: 52.6425,
    longitude: 5.0597,
    difficulty: 3,
    tags: ["harbor", "historic", "voc"],
    attribution: "Photo: Michielverbeek, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Hoorn",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_92",
    country: "NL",
    title: "Vlissingen",
    city: "Vlissingen",
    region: "Zeeland",
    latitude: 51.4508,
    longitude: 3.5701,
    difficulty: 4,
    tags: ["coastal", "boulevard", "zeeland"],
    attribution: "Photo: Marc Ryckaert (MJJR), Wikimedia Commons, CC BY-SA 3.0 nl.",
    sourceUrl: "https://en.wikipedia.org/wiki/Vlissingen",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_93",
    country: "NL",
    title: "Assen",
    city: "Assen",
    region: "Drenthe",
    latitude: 52.9926,
    longitude: 6.5642,
    difficulty: 4,
    tags: ["town", "drenthe"],
    attribution: "Photo: Groeneveld, G. (Fotograaf), Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Assen",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_94",
    country: "NL",
    title: "Heerlen",
    city: "Heerlen",
    region: "Limburg",
    latitude: 50.8882,
    longitude: 5.9795,
    difficulty: 4,
    tags: ["urban", "limburg"],
    attribution: "Photo: Norbert Schnitzler, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Heerlen",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_95",
    country: "NL",
    title: "Venlo",
    city: "Venlo",
    region: "Limburg",
    latitude: 51.3704,
    longitude: 6.1724,
    difficulty: 4,
    tags: ["river", "limburg", "town"],
    attribution: "Photo: Michielverbeek, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Venlo",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_96",
    country: "NL",
    title: "Almere",
    city: "Almere",
    region: "Flevoland",
    latitude: 52.3508,
    longitude: 5.2647,
    difficulty: 4,
    tags: ["modern", "polder", "city"],
    attribution: "Photo: Mark Ahsmann, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Almere",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_97",
    country: "NL",
    title: "Het Loo Palace",
    city: "Apeldoorn",
    region: "Gelderland",
    latitude: 52.2344,
    longitude: 5.9461,
    difficulty: 3,
    tags: ["palace", "historic", "garden"],
    attribution: "Photo: Zairon, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Het_Loo_Palace",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_98",
    country: "NL",
    title: "Harlingen",
    city: "Harlingen",
    region: "Friesland",
    latitude: 53.174,
    longitude: 5.427,
    difficulty: 4,
    tags: ["harbor", "friesland", "historic"],
    attribution: "Photo: S.Möller, Wikimedia Commons, Public domain.",
    sourceUrl: "https://en.wikipedia.org/wiki/Harlingen,_Netherlands",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_99",
    country: "NL",
    title: "West-Terschelling",
    city: "Terschelling",
    region: "Friesland",
    latitude: 53.3592,
    longitude: 5.2156,
    difficulty: 5,
    tags: ["island", "coastal", "lighthouse"],
    attribution: "Photo: MarcoSwart, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Terschelling",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_100",
    country: "NL",
    title: "Hindeloopen",
    city: "Hindeloopen",
    region: "Friesland",
    latitude: 52.943,
    longitude: 5.401,
    difficulty: 4,
    tags: ["village", "zuiderzee", "historic"],
    attribution: "Photo: Gouwenaar, Wikimedia Commons, CC0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Hindeloopen",
    sceneKind: "wikimedia",
  }),

  loc({
    id: "loc_101",
    country: "WORLD",
    nation: "FR",
    title: "Eiffel Tower",
    city: "Paris",
    region: "France",
    latitude: 48.85837,
    longitude: 2.29448,
    difficulty: 1,
    tags: ["iconic", "tower", "urban"],
    attribution: "Photo: Benh LIEU SONG, Wikimedia Commons, Public domain.",
    sourceUrl: "https://en.wikipedia.org/wiki/Eiffel_Tower",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_102",
    country: "WORLD",
    nation: "IT",
    title: "Colosseum",
    city: "Rome",
    region: "Italy",
    latitude: 41.8902,
    longitude: 12.4922,
    difficulty: 1,
    tags: ["iconic", "ruins", "historic"],
    attribution: "Photo: Diliff, Wikimedia Commons, CC BY-SA 2.5.",
    sourceUrl: "https://en.wikipedia.org/wiki/Colosseum",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_103",
    country: "WORLD",
    nation: "GB",
    title: "Elizabeth Tower",
    city: "London",
    region: "United Kingdom",
    latitude: 51.5007,
    longitude: -0.1246,
    difficulty: 1,
    tags: ["iconic", "clock", "urban"],
    attribution: "Photo: Diliff, Wikimedia Commons, CC BY 2.5.",
    sourceUrl: "https://en.wikipedia.org/wiki/Big_Ben",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_104",
    country: "WORLD",
    nation: "US",
    title: "Statue of Liberty",
    city: "New York",
    region: "United States",
    latitude: 40.6892,
    longitude: -74.0445,
    difficulty: 2,
    tags: ["iconic", "statue", "harbor"],
    attribution: "Photo: Elcobbola, Wikimedia Commons, Public domain.",
    sourceUrl: "https://en.wikipedia.org/wiki/Statue_of_Liberty",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_105",
    country: "WORLD",
    nation: "US",
    title: "Golden Gate Bridge",
    city: "San Francisco",
    region: "United States",
    latitude: 37.8199,
    longitude: -122.4783,
    difficulty: 2,
    tags: ["bridge", "iconic", "coastal"],
    attribution: "Photo: Rich Niewiroski Jr., Wikimedia Commons, CC BY 2.5.",
    sourceUrl: "https://en.wikipedia.org/wiki/Golden_Gate_Bridge",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_106",
    country: "WORLD",
    nation: "BR",
    title: "Christ the Redeemer",
    city: "Rio de Janeiro",
    region: "Brazil",
    latitude: -22.9519,
    longitude: -43.2105,
    difficulty: 2,
    tags: ["statue", "iconic", "mountain"],
    attribution: "Photo: Carlos esteban oviedo, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Christ_the_Redeemer_(statue)",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_107",
    country: "WORLD",
    nation: "PE",
    title: "Machu Picchu",
    city: "Cusco Region",
    region: "Peru",
    latitude: -13.1631,
    longitude: -72.545,
    difficulty: 2,
    tags: ["ruins", "mountain", "iconic"],
    attribution: "Photo: Pedro Szekely at https://www.flickr.com/photos/pedrosz/, Wikimedia Commons, CC BY-SA 2.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Machu_Picchu",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_108",
    country: "WORLD",
    nation: "AU",
    title: "Sydney Opera House",
    city: "Sydney",
    region: "Australia",
    latitude: -33.8568,
    longitude: 151.2153,
    difficulty: 1,
    tags: ["iconic", "harbor", "architecture"],
    attribution: "Photo: No machine-readable author provided. Roybb95~commonswiki assumed (base, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Sydney_Opera_House",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_109",
    country: "WORLD",
    nation: "IN",
    title: "Taj Mahal",
    city: "Agra",
    region: "India",
    latitude: 27.1751,
    longitude: 78.0421,
    difficulty: 1,
    tags: ["iconic", "mausoleum", "historic"],
    attribution: "Photo: Yann; edited by King of Hearts, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Taj_Mahal",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_110",
    country: "WORLD",
    nation: "JO",
    title: "Petra",
    city: "Ma'an",
    region: "Jordan",
    latitude: 30.3285,
    longitude: 35.4444,
    difficulty: 2,
    tags: ["ruins", "desert", "iconic"],
    attribution: "Photo: Azurfrog, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Petra",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_111",
    country: "WORLD",
    nation: "CN",
    title: "Great Wall at Mutianyu",
    city: "Beijing",
    region: "China",
    latitude: 40.431,
    longitude: 116.5704,
    difficulty: 2,
    tags: ["wall", "mountain", "iconic"],
    attribution: "Photo: Vincent Ndaku, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Great_Wall_of_China",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_112",
    country: "WORLD",
    nation: "JP",
    title: "Mount Fuji",
    city: "Honshu",
    region: "Japan",
    latitude: 35.3606,
    longitude: 138.7274,
    difficulty: 2,
    tags: ["mountain", "iconic", "volcano"],
    attribution: "Photo: Suicasmo, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Mount_Fuji",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_113",
    country: "WORLD",
    nation: "GR",
    title: "Oia",
    city: "Santorini",
    region: "Greece",
    latitude: 36.4618,
    longitude: 25.3753,
    difficulty: 2,
    tags: ["island", "coastal", "village"],
    attribution: "Photo: Danbu14, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Oia,_Greece",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_114",
    country: "WORLD",
    nation: "ES",
    title: "Sagrada Família",
    city: "Barcelona",
    region: "Spain",
    latitude: 41.4036,
    longitude: 2.1744,
    difficulty: 2,
    tags: ["church", "architecture", "iconic"],
    attribution: "Photo: Bernard Gagnon, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Sagrada_Fam%C3%ADlia",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_115",
    country: "WORLD",
    nation: "PT",
    title: "Belém Tower",
    city: "Lisbon",
    region: "Portugal",
    latitude: 38.6916,
    longitude: -9.216,
    difficulty: 3,
    tags: ["tower", "harbor", "historic"],
    attribution: "Photo: Alvesgaspar, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Bel%C3%A9m_Tower",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_116",
    country: "WORLD",
    nation: "CZ",
    title: "Prague Castle",
    city: "Prague",
    region: "Czechia",
    latitude: 50.091,
    longitude: 14.4016,
    difficulty: 2,
    tags: ["castle", "historic", "urban"],
    attribution: "Photo: Pudelek (Marcin Szala), Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Prague_Castle",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_117",
    country: "WORLD",
    nation: "DE",
    title: "Neuschwanstein",
    city: "Hohenschwangau",
    region: "Germany",
    latitude: 47.5576,
    longitude: 10.7498,
    difficulty: 2,
    tags: ["castle", "alpine", "iconic"],
    attribution: "Photo: Unknown authorUnknown author, Wikimedia Commons, Public domain.",
    sourceUrl: "https://en.wikipedia.org/wiki/Neuschwanstein_Castle",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_118",
    country: "WORLD",
    nation: "CH",
    title: "Matterhorn",
    city: "Zermatt",
    region: "Switzerland",
    latitude: 45.9763,
    longitude: 7.6586,
    difficulty: 2,
    tags: ["mountain", "alpine", "iconic"],
    attribution: "Photo: Photo: chil, on Camptocamp.org Derivative work:Zacharie Grossen, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Matterhorn",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_119",
    country: "WORLD",
    nation: "IS",
    title: "Hallgrímskirkja",
    city: "Reykjavík",
    region: "Iceland",
    latitude: 64.1417,
    longitude: -21.9266,
    difficulty: 3,
    tags: ["church", "urban", "nordic"],
    attribution: "Photo: Andreas Tille, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Hallgr%C3%ADmskirkja",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_120",
    country: "WORLD",
    nation: "NO",
    title: "Tromsø",
    city: "Tromsø",
    region: "Norway",
    latitude: 69.6492,
    longitude: 18.9553,
    difficulty: 4,
    tags: ["arctic", "harbor", "nordic"],
    attribution: "Photo: No machine-readable author provided. Jojo assumed (based on copyright, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Troms%C3%B8",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_121",
    country: "WORLD",
    nation: "SE",
    title: "Gamla Stan",
    city: "Stockholm",
    region: "Sweden",
    latitude: 59.325,
    longitude: 18.0708,
    difficulty: 3,
    tags: ["historic", "island", "urban"],
    attribution: "Photo: Arild Vågen, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Gamla_stan",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_122",
    country: "WORLD",
    nation: "FI",
    title: "Helsinki Cathedral",
    city: "Helsinki",
    region: "Finland",
    latitude: 60.1704,
    longitude: 24.9521,
    difficulty: 3,
    tags: ["church", "urban", "nordic"],
    attribution: "Photo: Jonik, Wikimedia Commons, CC BY-SA 2.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Helsinki_Cathedral",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_123",
    country: "WORLD",
    nation: "HR",
    title: "Dubrovnik",
    city: "Dubrovnik",
    region: "Croatia",
    latitude: 42.6406,
    longitude: 18.1103,
    difficulty: 3,
    tags: ["walls", "coastal", "historic"],
    attribution: "Photo: Diego Delso, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Dubrovnik",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_124",
    country: "WORLD",
    nation: "HU",
    title: "Hungarian Parliament",
    city: "Budapest",
    region: "Hungary",
    latitude: 47.507,
    longitude: 19.0456,
    difficulty: 2,
    tags: ["civic", "danube", "architecture"],
    attribution: "Photo: Dirk Beyer, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Hungarian_Parliament_Building",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_125",
    country: "WORLD",
    nation: "IE",
    title: "Ha'penny Bridge",
    city: "Dublin",
    region: "Ireland",
    latitude: 53.3463,
    longitude: -6.263,
    difficulty: 3,
    tags: ["bridge", "urban", "river"],
    attribution: "Photo: Katina Rogers, Wikimedia Commons, CC BY 2.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Ha%27penny_Bridge",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_126",
    country: "WORLD",
    nation: "GB",
    title: "Edinburgh Castle",
    city: "Edinburgh",
    region: "United Kingdom",
    latitude: 55.9486,
    longitude: -3.1999,
    difficulty: 2,
    tags: ["castle", "rock", "historic"],
    attribution: "Photo: Syrio, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Edinburgh_Castle",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_127",
    country: "WORLD",
    nation: "US",
    title: "Times Square",
    city: "New York",
    region: "United States",
    latitude: 40.758,
    longitude: -73.9855,
    difficulty: 2,
    tags: ["urban", "neon", "iconic"],
    attribution: "Photo: David Shankbone, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Times_Square",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_128",
    country: "WORLD",
    nation: "CA",
    title: "Lake Louise",
    city: "Banff",
    region: "Canada",
    latitude: 51.4254,
    longitude: -116.1773,
    difficulty: 3,
    tags: ["lake", "mountain", "park"],
    attribution: "Photo: Gorgo, Wikimedia Commons, Public domain.",
    sourceUrl: "https://en.wikipedia.org/wiki/Lake_Louise,_Alberta",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_129",
    country: "WORLD",
    nation: "MX",
    title: "Chichén Itzá",
    city: "Yucatán",
    region: "Mexico",
    latitude: 20.6843,
    longitude: -88.5678,
    difficulty: 2,
    tags: ["ruins", "pyramid", "iconic"],
    attribution: "Photo: Daniel Schwen, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Chichen_Itza",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_130",
    country: "WORLD",
    nation: "AR",
    title: "Iguazú Falls",
    city: "Misiones",
    region: "Argentina",
    latitude: -25.6953,
    longitude: -54.4367,
    difficulty: 3,
    tags: ["waterfall", "jungle", "iconic"],
    attribution: "Photo: Emesbe at Dutch Wikipedia, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Iguazu_Falls",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_131",
    country: "WORLD",
    nation: "CL",
    title: "Torres del Paine",
    city: "Magallanes",
    region: "Chile",
    latitude: -50.9423,
    longitude: -73.4068,
    difficulty: 3,
    tags: ["mountain", "patagonia", "park"],
    attribution: "Photo: Miguel Vieira (talk · contribs), Wikimedia Commons, Public domain.",
    sourceUrl: "https://en.wikipedia.org/wiki/Torres_del_Paine_National_Park",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_132",
    country: "WORLD",
    nation: "KH",
    title: "Angkor Wat",
    city: "Siem Reap",
    region: "Cambodia",
    latitude: 13.4125,
    longitude: 103.867,
    difficulty: 2,
    tags: ["temple", "ruins", "iconic"],
    attribution: "Photo: Bjørn Christian Tørrissen, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Angkor_Wat",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_133",
    country: "WORLD",
    nation: "VN",
    title: "Hạ Long Bay",
    city: "Quảng Ninh",
    region: "Vietnam",
    latitude: 20.9101,
    longitude: 107.1839,
    difficulty: 3,
    tags: ["bay", "karst", "boats"],
    attribution: "Photo: Thomas Hirsch / User:Ravn, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Ha_Long_Bay",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_134",
    country: "WORLD",
    nation: "TH",
    title: "Wat Arun",
    city: "Bangkok",
    region: "Thailand",
    latitude: 13.7437,
    longitude: 100.4888,
    difficulty: 3,
    tags: ["temple", "river", "urban"],
    attribution: "Photo: Cun Cun, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Wat_Arun",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_135",
    country: "WORLD",
    nation: "ID",
    title: "Tanah Lot",
    city: "Bali",
    region: "Indonesia",
    latitude: -8.6212,
    longitude: 115.0868,
    difficulty: 3,
    tags: ["temple", "coastal", "island"],
    attribution: "Photo: Kandoi.sid, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Tanah_Lot",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_136",
    country: "WORLD",
    nation: "KR",
    title: "Gyeongbokgung",
    city: "Seoul",
    region: "South Korea",
    latitude: 37.5796,
    longitude: 126.977,
    difficulty: 3,
    tags: ["palace", "urban", "historic"],
    attribution: "Photo: 서울관광 아카이브, Wikimedia Commons, KOGL Type 1.",
    sourceUrl: "https://en.wikipedia.org/wiki/Gyeongbokgung",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_137",
    country: "WORLD",
    nation: "SG",
    title: "Marina Bay Sands",
    city: "Singapore",
    region: "Singapore",
    latitude: 1.2834,
    longitude: 103.8607,
    difficulty: 2,
    tags: ["iconic", "skyline", "harbor"],
    attribution: "Photo: Someformofhuman, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Marina_Bay_Sands",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_138",
    country: "WORLD",
    nation: "HK",
    title: "Victoria Peak",
    city: "Hong Kong",
    region: "Hong Kong",
    latitude: 22.2759,
    longitude: 114.1455,
    difficulty: 3,
    tags: ["skyline", "mountain", "harbor"],
    attribution: "Photo: Base64, retouched by CarolSpears, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Victoria_Peak",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_139",
    country: "WORLD",
    nation: "EG",
    title: "Giza Pyramids",
    city: "Giza",
    region: "Egypt",
    latitude: 29.9792,
    longitude: 31.1342,
    difficulty: 1,
    tags: ["pyramid", "desert", "iconic"],
    attribution: "Photo: Ricardo Liberato, Wikimedia Commons, CC BY-SA 2.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Giza_pyramid_complex",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_140",
    country: "WORLD",
    nation: "MA",
    title: "Jemaa el-Fnaa",
    city: "Marrakesh",
    region: "Morocco",
    latitude: 31.6258,
    longitude: -7.9891,
    difficulty: 3,
    tags: ["square", "medina", "urban"],
    attribution: "Photo: Yair Haklai, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Jemaa_el-Fnaa",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_141",
    country: "WORLD",
    nation: "TZ",
    title: "Serengeti",
    city: "Serengeti",
    region: "Tanzania",
    latitude: -2.3333,
    longitude: 34.8333,
    difficulty: 4,
    tags: ["savanna", "wildlife", "park"],
    attribution: "Photo: Richard Mortel from Riyadh, Saudi Arabia, Wikimedia Commons, CC BY 2.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Serengeti",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_142",
    country: "WORLD",
    nation: "ZM",
    title: "Victoria Falls",
    city: "Livingstone",
    region: "Zambia",
    latitude: -17.9243,
    longitude: 25.8572,
    difficulty: 3,
    tags: ["waterfall", "iconic", "river"],
    attribution: "Photo: Ferdinand Reus, Wikimedia Commons, CC BY-SA 2.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Victoria_Falls",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_143",
    country: "WORLD",
    nation: "AU",
    title: "Uluru",
    city: "Northern Territory",
    region: "Australia",
    latitude: -25.3444,
    longitude: 131.0369,
    difficulty: 2,
    tags: ["rock", "desert", "iconic"],
    attribution: "Photo: Kate Branch, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Uluru",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_144",
    country: "WORLD",
    nation: "NZ",
    title: "Milford Sound",
    city: "Fiordland",
    region: "New Zealand",
    latitude: -44.641,
    longitude: 167.896,
    difficulty: 3,
    tags: ["fjord", "mountain", "water"],
    attribution: "Photo: Krzysztof Golik, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Milford_Sound",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_145",
    country: "WORLD",
    nation: "TR",
    title: "Cappadocia",
    city: "Göreme",
    region: "Turkey",
    latitude: 38.6431,
    longitude: 34.8289,
    difficulty: 3,
    tags: ["rock", "valley", "balloons"],
    attribution: "Photo: Brocken Inaglory, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Cappadocia",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_146",
    country: "WORLD",
    nation: "TR",
    title: "Sultan Ahmed Mosque",
    city: "Istanbul",
    region: "Turkey",
    latitude: 41.0054,
    longitude: 28.9768,
    difficulty: 2,
    tags: ["mosque", "historic", "urban"],
    attribution: "Photo: Wikimedia Commons contributors, Wikimedia Commons, Public domain.",
    sourceUrl: "https://en.wikipedia.org/wiki/Blue_Mosque,_Istanbul",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_147",
    country: "WORLD",
    nation: "GR",
    title: "Acropolis",
    city: "Athens",
    region: "Greece",
    latitude: 37.9715,
    longitude: 23.7267,
    difficulty: 2,
    tags: ["ruins", "iconic", "hill"],
    attribution: "Photo: Giles Laurent, Wikimedia Commons, CC BY-SA 4.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Acropolis_of_Athens",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_148",
    country: "WORLD",
    nation: "IT",
    title: "Grand Canal",
    city: "Venice",
    region: "Italy",
    latitude: 45.4378,
    longitude: 12.3358,
    difficulty: 2,
    tags: ["canal", "urban", "iconic"],
    attribution: "Photo: This Photo was taken by Wolfgang Moroder. Feel free to use my photo, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Grand_Canal_(Venice)",
    sceneKind: "wikimedia",
  }),
  loc({
    id: "loc_149",
    country: "WORLD",
    nation: "US",
    title: "Grand Canyon",
    city: "Arizona",
    region: "United States",
    latitude: 36.0544,
    longitude: -112.1401,
    difficulty: 2,
    tags: ["canyon", "desert", "iconic"],
    attribution: "Photo: Tuxyso, Wikimedia Commons, CC BY-SA 3.0.",
    sourceUrl: "https://en.wikipedia.org/wiki/Grand_Canyon",
    sceneKind: "wikimedia",
  }),
];
