import type { GeoLocation } from "./types.ts";

const V = "2026-09-21";

function commons(file: string): string {
  return `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}?width=1280`;
}

function loc(
  partial: Omit<GeoLocation, "verifiedAt" | "enabled"> & { sceneUrl?: string },
): GeoLocation {
  return {
    ...partial,
    verifiedAt: V,
    enabled: true,
    sceneUrl: partial.sceneUrl ?? `/locations/${partial.id}.jpg`,
  };
}

/** +15 ZA, +15 NL, +49 WORLD → 149-site pool with the existing 70. */
export const PACK_LOCATIONS: GeoLocation[] = [
  loc({
    id: "loc_71",
    country: "ZA",
    title: "Bo-Kaap",
    city: "Cape Town",
    region: "Western Cape",
    latitude: -33.9215,
    longitude: 18.4152,
    difficulty: 3,
    tags: ["urban", "color", "historic"],
    attribution: "Wikimedia Commons. Wikipedia: Bo-Kaap.",
    sourceUrl: "https://en.wikipedia.org/wiki/Bo-Kaap",
    sceneKind: "wikimedia",
    sceneUrl: commons("Bo-Kaap_01.jpg"),
  }),
  loc({
    id: "loc_72",
    country: "ZA",
    title: "Castle of Good Hope",
    city: "Cape Town",
    region: "Western Cape",
    latitude: -33.9258,
    longitude: 18.4278,
    difficulty: 3,
    tags: ["fort", "historic", "urban"],
    attribution: "Wikimedia Commons. Wikipedia: Castle of Good Hope.",
    sourceUrl: "https://en.wikipedia.org/wiki/Castle_of_Good_Hope",
    sceneKind: "wikimedia",
    sceneUrl: commons("Castle_of_Good_Hope,_Cape_Town.JPG"),
  }),
  loc({
    id: "loc_73",
    country: "ZA",
    title: "Apartheid Museum",
    city: "Johannesburg",
    region: "Gauteng",
    latitude: -26.2366,
    longitude: 28.0092,
    difficulty: 4,
    tags: ["museum", "urban", "historic"],
    attribution: "Wikimedia Commons. Wikipedia: Apartheid Museum.",
    sourceUrl: "https://en.wikipedia.org/wiki/Apartheid_Museum",
    sceneKind: "wikimedia",
    sceneUrl: commons("Apartheid_Museum.jpg"),
  }),
  loc({
    id: "loc_74",
    country: "ZA",
    title: "FNB Stadium",
    city: "Soweto",
    region: "Gauteng",
    latitude: -26.2348,
    longitude: 27.9826,
    difficulty: 3,
    tags: ["stadium", "urban", "iconic"],
    attribution: "Wikimedia Commons. Wikipedia: FNB Stadium.",
    sourceUrl: "https://en.wikipedia.org/wiki/FNB_Stadium",
    sceneKind: "wikimedia",
    sceneUrl: commons("Soccer_City.jpg"),
  }),
  loc({
    id: "loc_75",
    country: "ZA",
    title: "East London City Hall",
    city: "East London",
    region: "Eastern Cape",
    latitude: -33.0153,
    longitude: 27.9116,
    difficulty: 4,
    tags: ["civic", "urban", "coastal"],
    attribution: "Wikimedia Commons. Wikipedia: East London, South Africa.",
    sourceUrl: "https://en.wikipedia.org/wiki/East_London,_South_Africa",
    sceneKind: "wikimedia",
    sceneUrl: commons("East_London_City_Hall.jpg"),
  }),
  loc({
    id: "loc_76",
    country: "ZA",
    title: "Upington",
    city: "Upington",
    region: "Northern Cape",
    latitude: -28.4478,
    longitude: 21.2561,
    difficulty: 4,
    tags: ["town", "desert", "river"],
    attribution: "Wikimedia Commons. Wikipedia: Upington.",
    sourceUrl: "https://en.wikipedia.org/wiki/Upington",
    sceneKind: "wikimedia",
    sceneUrl: commons("Upington,_South_Africa.jpg"),
  }),
  loc({
    id: "loc_77",
    country: "ZA",
    title: "Langebaan Lagoon",
    city: "Langebaan",
    region: "Western Cape",
    latitude: -33.0919,
    longitude: 18.0311,
    difficulty: 4,
    tags: ["lagoon", "coastal", "west-coast"],
    attribution: "Wikimedia Commons. Wikipedia: Langebaan.",
    sourceUrl: "https://en.wikipedia.org/wiki/Langebaan",
    sceneKind: "wikimedia",
    sceneUrl: commons("Langebaan_Lagoon.jpg"),
  }),
  loc({
    id: "loc_78",
    country: "ZA",
    title: "Wilderness Beach",
    city: "Wilderness",
    region: "Western Cape",
    latitude: -33.9936,
    longitude: 22.575,
    difficulty: 4,
    tags: ["beach", "coastal", "garden-route"],
    attribution: "Wikimedia Commons. Wikipedia: Wilderness, Western Cape.",
    sourceUrl: "https://en.wikipedia.org/wiki/Wilderness,_Western_Cape",
    sceneKind: "wikimedia",
    sceneUrl: commons("Wilderness_Beach.jpg"),
  }),
  loc({
    id: "loc_79",
    country: "ZA",
    title: "Hluhluwe",
    city: "Hluhluwe",
    region: "KwaZulu-Natal",
    latitude: -28.038,
    longitude: 32.286,
    difficulty: 4,
    tags: ["wildlife", "park", "bush"],
    attribution: "Wikimedia Commons. Wikipedia: Hluhluwe–iMfolozi Park.",
    sourceUrl: "https://en.wikipedia.org/wiki/Hluhluwe%E2%80%93Imfolozi_Park",
    sceneKind: "wikimedia",
    sceneUrl: commons("Hluhluwe_Umfolozi.jpg"),
  }),
  loc({
    id: "loc_80",
    country: "ZA",
    title: "Pilanesberg",
    city: "Pilanesberg",
    region: "North West",
    latitude: -25.241,
    longitude: 27.081,
    difficulty: 4,
    tags: ["wildlife", "crater", "park"],
    attribution: "Wikimedia Commons. Wikipedia: Pilanesberg National Park.",
    sourceUrl: "https://en.wikipedia.org/wiki/Pilanesberg_National_Park",
    sceneKind: "wikimedia",
    sceneUrl: commons("Pilanesberg_National_Park.jpg"),
  }),
  loc({
    id: "loc_81",
    country: "ZA",
    title: "Clarens",
    city: "Clarens",
    region: "Free State",
    latitude: -28.5147,
    longitude: 28.4192,
    difficulty: 4,
    tags: ["village", "mountain", "art"],
    attribution: "Wikimedia Commons. Wikipedia: Clarens, Free State.",
    sourceUrl: "https://en.wikipedia.org/wiki/Clarens,_Free_State",
    sceneKind: "wikimedia",
    sceneUrl: commons("Clarens_Free_State.jpg"),
  }),
  loc({
    id: "loc_82",
    country: "ZA",
    title: "Port St Johns",
    city: "Port St Johns",
    region: "Eastern Cape",
    latitude: -31.6286,
    longitude: 29.5369,
    difficulty: 4,
    tags: ["coastal", "wild-coast", "town"],
    attribution: "Wikimedia Commons. Wikipedia: Port St. Johns.",
    sourceUrl: "https://en.wikipedia.org/wiki/Port_St._Johns",
    sceneKind: "wikimedia",
    sceneUrl: commons("Port_St_Johns.jpg"),
  }),
  loc({
    id: "loc_83",
    country: "ZA",
    title: "Springbok",
    city: "Springbok",
    region: "Northern Cape",
    latitude: -29.6643,
    longitude: 17.8856,
    difficulty: 5,
    tags: ["desert", "namaqualand", "town"],
    attribution: "Wikimedia Commons. Wikipedia: Springbok, Northern Cape.",
    sourceUrl: "https://en.wikipedia.org/wiki/Springbok,_Northern_Cape",
    sceneKind: "wikimedia",
    sceneUrl: commons("Springbok_Northern_Cape.jpg"),
  }),
  loc({
    id: "loc_84",
    country: "ZA",
    title: "Mahikeng",
    city: "Mahikeng",
    region: "North West",
    latitude: -25.86,
    longitude: 25.644,
    difficulty: 4,
    tags: ["town", "historic", "inland"],
    attribution: "Wikimedia Commons. Wikipedia: Mahikeng.",
    sourceUrl: "https://en.wikipedia.org/wiki/Mahikeng",
    sceneKind: "wikimedia",
    sceneUrl: commons("Mahikeng.jpg"),
  }),
  loc({
    id: "loc_85",
    country: "ZA",
    title: "Saldanha Bay",
    city: "Saldanha",
    region: "Western Cape",
    latitude: -33.0117,
    longitude: 17.9442,
    difficulty: 4,
    tags: ["harbor", "coastal", "industrial"],
    attribution: "Wikimedia Commons. Wikipedia: Saldanha Bay.",
    sourceUrl: "https://en.wikipedia.org/wiki/Saldanha_Bay",
    sceneKind: "wikimedia",
    sceneUrl: commons("Saldanha_Bay.jpg"),
  }),

  loc({
    id: "loc_86",
    country: "NL",
    title: "Tilburg",
    city: "Tilburg",
    region: "North Brabant",
    latitude: 51.5555,
    longitude: 5.0913,
    difficulty: 4,
    tags: ["urban", "city", "brabant"],
    attribution: "Wikimedia Commons. Wikipedia: Tilburg.",
    sourceUrl: "https://en.wikipedia.org/wiki/Tilburg",
    sceneKind: "wikimedia",
    sceneUrl: commons("Tilburg_centrum.jpg"),
  }),
  loc({
    id: "loc_87",
    country: "NL",
    title: "Zwolle",
    city: "Zwolle",
    region: "Overijssel",
    latitude: 52.5168,
    longitude: 6.083,
    difficulty: 4,
    tags: ["historic", "city", "sassenpoort"],
    attribution: "Wikimedia Commons. Wikipedia: Zwolle.",
    sourceUrl: "https://en.wikipedia.org/wiki/Zwolle",
    sceneKind: "wikimedia",
    sceneUrl: commons("Sassenpoort_Zwolle.jpg"),
  }),
  loc({
    id: "loc_88",
    country: "NL",
    title: "Enschede",
    city: "Enschede",
    region: "Overijssel",
    latitude: 52.2215,
    longitude: 6.8937,
    difficulty: 4,
    tags: ["urban", "city"],
    attribution: "Wikimedia Commons. Wikipedia: Enschede.",
    sourceUrl: "https://en.wikipedia.org/wiki/Enschede",
    sceneKind: "wikimedia",
    sceneUrl: commons("Enschede_Grote_Markt.jpg"),
  }),
  loc({
    id: "loc_89",
    country: "NL",
    title: "Deventer",
    city: "Deventer",
    region: "Overijssel",
    latitude: 52.2516,
    longitude: 6.1639,
    difficulty: 3,
    tags: ["historic", "ijssel", "town"],
    attribution: "Wikimedia Commons. Wikipedia: Deventer.",
    sourceUrl: "https://en.wikipedia.org/wiki/Deventer",
    sceneKind: "wikimedia",
    sceneUrl: commons("Deventer_Bergkerk.jpg"),
  }),
  loc({
    id: "loc_90",
    country: "NL",
    title: "Kampen",
    city: "Kampen",
    region: "Overijssel",
    latitude: 52.555,
    longitude: 5.9114,
    difficulty: 4,
    tags: ["hanseatic", "river", "historic"],
    attribution: "Wikimedia Commons. Wikipedia: Kampen, Overijssel.",
    sourceUrl: "https://en.wikipedia.org/wiki/Kampen,_Overijssel",
    sceneKind: "wikimedia",
    sceneUrl: commons("Kampen_Bovenkerk.jpg"),
  }),
  loc({
    id: "loc_91",
    country: "NL",
    title: "Hoorn",
    city: "Hoorn",
    region: "North Holland",
    latitude: 52.6425,
    longitude: 5.0597,
    difficulty: 3,
    tags: ["harbor", "historic", "voc"],
    attribution: "Wikimedia Commons. Wikipedia: Hoorn.",
    sourceUrl: "https://en.wikipedia.org/wiki/Hoorn",
    sceneKind: "wikimedia",
    sceneUrl: commons("Hoorn_Hoofdtoren.jpg"),
  }),
  loc({
    id: "loc_92",
    country: "NL",
    title: "Vlissingen",
    city: "Vlissingen",
    region: "Zeeland",
    latitude: 51.4508,
    longitude: 3.5701,
    difficulty: 4,
    tags: ["coastal", "boulevard", "zeeland"],
    attribution: "Wikimedia Commons. Wikipedia: Vlissingen.",
    sourceUrl: "https://en.wikipedia.org/wiki/Vlissingen",
    sceneKind: "wikimedia",
    sceneUrl: commons("Vlissingen_boulevard.jpg"),
  }),
  loc({
    id: "loc_93",
    country: "NL",
    title: "Assen",
    city: "Assen",
    region: "Drenthe",
    latitude: 52.9926,
    longitude: 6.5642,
    difficulty: 4,
    tags: ["town", "drenthe"],
    attribution: "Wikimedia Commons. Wikipedia: Assen.",
    sourceUrl: "https://en.wikipedia.org/wiki/Assen",
    sceneKind: "wikimedia",
    sceneUrl: commons("Assen_Drents_Museum.jpg"),
  }),
  loc({
    id: "loc_94",
    country: "NL",
    title: "Heerlen",
    city: "Heerlen",
    region: "Limburg",
    latitude: 50.8882,
    longitude: 5.9795,
    difficulty: 4,
    tags: ["urban", "limburg"],
    attribution: "Wikimedia Commons. Wikipedia: Heerlen.",
    sourceUrl: "https://en.wikipedia.org/wiki/Heerlen",
    sceneKind: "wikimedia",
    sceneUrl: commons("Heerlen_Pancratiuskerk.jpg"),
  }),
  loc({
    id: "loc_95",
    country: "NL",
    title: "Venlo",
    city: "Venlo",
    region: "Limburg",
    latitude: 51.3704,
    longitude: 6.1724,
    difficulty: 4,
    tags: ["river", "limburg", "town"],
    attribution: "Wikimedia Commons. Wikipedia: Venlo.",
    sourceUrl: "https://en.wikipedia.org/wiki/Venlo",
    sceneKind: "wikimedia",
    sceneUrl: commons("Venlo_stadhuis.jpg"),
  }),
  loc({
    id: "loc_96",
    country: "NL",
    title: "Almere",
    city: "Almere",
    region: "Flevoland",
    latitude: 52.3508,
    longitude: 5.2647,
    difficulty: 4,
    tags: ["modern", "polder", "city"],
    attribution: "Wikimedia Commons. Wikipedia: Almere.",
    sourceUrl: "https://en.wikipedia.org/wiki/Almere",
    sceneKind: "wikimedia",
    sceneUrl: commons("Almere_skyline.jpg"),
  }),
  loc({
    id: "loc_97",
    country: "NL",
    title: "Het Loo Palace",
    city: "Apeldoorn",
    region: "Gelderland",
    latitude: 52.2344,
    longitude: 5.9461,
    difficulty: 3,
    tags: ["palace", "historic", "garden"],
    attribution: "Wikimedia Commons. Wikipedia: Het Loo Palace.",
    sourceUrl: "https://en.wikipedia.org/wiki/Het_Loo_Palace",
    sceneKind: "wikimedia",
    sceneUrl: commons("Paleis_Het_Loo.jpg"),
  }),
  loc({
    id: "loc_98",
    country: "NL",
    title: "Harlingen",
    city: "Harlingen",
    region: "Friesland",
    latitude: 53.174,
    longitude: 5.427,
    difficulty: 4,
    tags: ["harbor", "friesland", "historic"],
    attribution: "Wikimedia Commons. Wikipedia: Harlingen, Netherlands.",
    sourceUrl: "https://en.wikipedia.org/wiki/Harlingen,_Netherlands",
    sceneKind: "wikimedia",
    sceneUrl: commons("Harlingen_haven.jpg"),
  }),
  loc({
    id: "loc_99",
    country: "NL",
    title: "West-Terschelling",
    city: "Terschelling",
    region: "Friesland",
    latitude: 53.3592,
    longitude: 5.2156,
    difficulty: 5,
    tags: ["island", "coastal", "lighthouse"],
    attribution: "Wikimedia Commons. Wikipedia: Terschelling.",
    sourceUrl: "https://en.wikipedia.org/wiki/Terschelling",
    sceneKind: "wikimedia",
    sceneUrl: commons("Brandaris_Terschelling.jpg"),
  }),
  loc({
    id: "loc_100",
    country: "NL",
    title: "Hindeloopen",
    city: "Hindeloopen",
    region: "Friesland",
    latitude: 52.943,
    longitude: 5.401,
    difficulty: 4,
    tags: ["village", "zuiderzee", "historic"],
    attribution: "Wikimedia Commons. Wikipedia: Hindeloopen.",
    sourceUrl: "https://en.wikipedia.org/wiki/Hindeloopen",
    sceneKind: "wikimedia",
    sceneUrl: commons("Hindeloopen.jpg"),
  }),

  loc({
    id: "loc_101",
    country: "WORLD",
    nation: "FR",
    title: "Eiffel Tower",
    city: "Paris",
    region: "France",
    latitude: 48.85837,
    longitude: 2.29448,
    difficulty: 1,
    tags: ["iconic", "tower", "urban"],
    attribution: "Wikimedia Commons. Wikipedia: Eiffel Tower.",
    sourceUrl: "https://en.wikipedia.org/wiki/Eiffel_Tower",
    sceneKind: "wikimedia",
    sceneUrl: commons("Tour_Eiffel_Wikimedia_Commons.jpg"),
  }),
  loc({
    id: "loc_102",
    country: "WORLD",
    nation: "IT",
    title: "Colosseum",
    city: "Rome",
    region: "Italy",
    latitude: 41.8902,
    longitude: 12.4922,
    difficulty: 1,
    tags: ["iconic", "ruins", "historic"],
    attribution: "Wikimedia Commons. Wikipedia: Colosseum.",
    sourceUrl: "https://en.wikipedia.org/wiki/Colosseum",
    sceneKind: "wikimedia",
    sceneUrl: commons("Colosseum_in_Rome,_Italy_-_April_2007.jpg"),
  }),
  loc({
    id: "loc_103",
    country: "WORLD",
    nation: "GB",
    title: "Elizabeth Tower",
    city: "London",
    region: "United Kingdom",
    latitude: 51.5007,
    longitude: -0.1246,
    difficulty: 1,
    tags: ["iconic", "clock", "urban"],
    attribution: "Wikimedia Commons. Wikipedia: Big Ben.",
    sourceUrl: "https://en.wikipedia.org/wiki/Big_Ben",
    sceneKind: "wikimedia",
    sceneUrl: commons("Clock_Tower_-_Palace_of_Westminster,_London_-_May_2007.jpg"),
  }),
  loc({
    id: "loc_104",
    country: "WORLD",
    nation: "US",
    title: "Statue of Liberty",
    city: "New York",
    region: "United States",
    latitude: 40.6892,
    longitude: -74.0445,
    difficulty: 2,
    tags: ["iconic", "statue", "harbor"],
    attribution: "Wikimedia Commons. Wikipedia: Statue of Liberty.",
    sourceUrl: "https://en.wikipedia.org/wiki/Statue_of_Liberty",
    sceneKind: "wikimedia",
    sceneUrl: commons("Statue_of_Liberty_7.jpg"),
  }),
  loc({
    id: "loc_105",
    country: "WORLD",
    nation: "US",
    title: "Golden Gate Bridge",
    city: "San Francisco",
    region: "United States",
    latitude: 37.8199,
    longitude: -122.4783,
    difficulty: 2,
    tags: ["bridge", "iconic", "coastal"],
    attribution: "Wikimedia Commons. Wikipedia: Golden Gate Bridge.",
    sourceUrl: "https://en.wikipedia.org/wiki/Golden_Gate_Bridge",
    sceneKind: "wikimedia",
    sceneUrl: commons("GoldenGateBridge-001.jpg"),
  }),
  loc({
    id: "loc_106",
    country: "WORLD",
    nation: "BR",
    title: "Christ the Redeemer",
    city: "Rio de Janeiro",
    region: "Brazil",
    latitude: -22.9519,
    longitude: -43.2105,
    difficulty: 2,
    tags: ["statue", "iconic", "mountain"],
    attribution: "Wikimedia Commons. Wikipedia: Christ the Redeemer (statue).",
    sourceUrl: "https://en.wikipedia.org/wiki/Christ_the_Redeemer_(statue)",
    sceneKind: "wikimedia",
    sceneUrl: commons("Cristo_Redentor_Rio_de_Janeiro.jpg"),
  }),
  loc({
    id: "loc_107",
    country: "WORLD",
    nation: "PE",
    title: "Machu Picchu",
    city: "Cusco Region",
    region: "Peru",
    latitude: -13.1631,
    longitude: -72.545,
    difficulty: 2,
    tags: ["ruins", "mountain", "iconic"],
    attribution: "Wikimedia Commons. Wikipedia: Machu Picchu.",
    sourceUrl: "https://en.wikipedia.org/wiki/Machu_Picchu",
    sceneKind: "wikimedia",
    sceneUrl: commons("Machu_Picchu,_Peru.jpg"),
  }),
  loc({
    id: "loc_108",
    country: "WORLD",
    nation: "AU",
    title: "Sydney Opera House",
    city: "Sydney",
    region: "Australia",
    latitude: -33.8568,
    longitude: 151.2153,
    difficulty: 1,
    tags: ["iconic", "harbor", "architecture"],
    attribution: "Wikimedia Commons. Wikipedia: Sydney Opera House.",
    sourceUrl: "https://en.wikipedia.org/wiki/Sydney_Opera_House",
    sceneKind: "wikimedia",
    sceneUrl: commons("Sydney_Opera_House_Sails.jpg"),
  }),
  loc({
    id: "loc_109",
    country: "WORLD",
    nation: "IN",
    title: "Taj Mahal",
    city: "Agra",
    region: "India",
    latitude: 27.1751,
    longitude: 78.0421,
    difficulty: 1,
    tags: ["iconic", "mausoleum", "historic"],
    attribution: "Wikimedia Commons. Wikipedia: Taj Mahal.",
    sourceUrl: "https://en.wikipedia.org/wiki/Taj_Mahal",
    sceneKind: "wikimedia",
    sceneUrl: commons("Taj_Mahal,_Agra,_India_edit2.jpg"),
  }),
  loc({
    id: "loc_110",
    country: "WORLD",
    nation: "JO",
    title: "Petra",
    city: "Ma'an",
    region: "Jordan",
    latitude: 30.3285,
    longitude: 35.4444,
    difficulty: 2,
    tags: ["ruins", "desert", "iconic"],
    attribution: "Wikimedia Commons. Wikipedia: Petra.",
    sourceUrl: "https://en.wikipedia.org/wiki/Petra",
    sceneKind: "wikimedia",
    sceneUrl: commons("Al_Khazneh_Petra_edit_1.jpg"),
  }),
  loc({
    id: "loc_111",
    country: "WORLD",
    nation: "CN",
    title: "Great Wall at Mutianyu",
    city: "Beijing",
    region: "China",
    latitude: 40.431,
    longitude: 116.5704,
    difficulty: 2,
    tags: ["wall", "mountain", "iconic"],
    attribution: "Wikimedia Commons. Wikipedia: Great Wall of China.",
    sourceUrl: "https://en.wikipedia.org/wiki/Great_Wall_of_China",
    sceneKind: "wikimedia",
    sceneUrl: commons("The_Great_Wall_of_China_at_Jinshanling.jpg"),
  }),
  loc({
    id: "loc_112",
    country: "WORLD",
    nation: "JP",
    title: "Mount Fuji",
    city: "Honshu",
    region: "Japan",
    latitude: 35.3606,
    longitude: 138.7274,
    difficulty: 2,
    tags: ["mountain", "iconic", "volcano"],
    attribution: "Wikimedia Commons. Wikipedia: Mount Fuji.",
    sourceUrl: "https://en.wikipedia.org/wiki/Mount_Fuji",
    sceneKind: "wikimedia",
    sceneUrl: commons("Mount_Fuji_from_Hotel_Mt_Fuji.jpg"),
  }),
  loc({
    id: "loc_113",
    country: "WORLD",
    nation: "GR",
    title: "Oia",
    city: "Santorini",
    region: "Greece",
    latitude: 36.4618,
    longitude: 25.3753,
    difficulty: 2,
    tags: ["island", "coastal", "village"],
    attribution: "Wikimedia Commons. Wikipedia: Oia, Greece.",
    sourceUrl: "https://en.wikipedia.org/wiki/Oia,_Greece",
    sceneKind: "wikimedia",
    sceneUrl: commons("Santorini_Oia.jpg"),
  }),
  loc({
    id: "loc_114",
    country: "WORLD",
    nation: "ES",
    title: "Sagrada Família",
    city: "Barcelona",
    region: "Spain",
    latitude: 41.4036,
    longitude: 2.1744,
    difficulty: 2,
    tags: ["church", "architecture", "iconic"],
    attribution: "Wikimedia Commons. Wikipedia: Sagrada Família.",
    sourceUrl: "https://en.wikipedia.org/wiki/Sagrada_Fam%C3%ADlia",
    sceneKind: "wikimedia",
    sceneUrl: commons("Sagrada_Familia_01.jpg"),
  }),
  loc({
    id: "loc_115",
    country: "WORLD",
    nation: "PT",
    title: "Belém Tower",
    city: "Lisbon",
    region: "Portugal",
    latitude: 38.6916,
    longitude: -9.216,
    difficulty: 3,
    tags: ["tower", "harbor", "historic"],
    attribution: "Wikimedia Commons. Wikipedia: Belém Tower.",
    sourceUrl: "https://en.wikipedia.org/wiki/Bel%C3%A9m_Tower",
    sceneKind: "wikimedia",
    sceneUrl: commons("Torre_Belém_April_2009-4a.jpg"),
  }),
  loc({
    id: "loc_116",
    country: "WORLD",
    nation: "CZ",
    title: "Prague Castle",
    city: "Prague",
    region: "Czechia",
    latitude: 50.091,
    longitude: 14.4016,
    difficulty: 2,
    tags: ["castle", "historic", "urban"],
    attribution: "Wikimedia Commons. Wikipedia: Prague Castle.",
    sourceUrl: "https://en.wikipedia.org/wiki/Prague_Castle",
    sceneKind: "wikimedia",
    sceneUrl: commons("Prague_Castle_from_Petrin.jpg"),
  }),
  loc({
    id: "loc_117",
    country: "WORLD",
    nation: "DE",
    title: "Neuschwanstein",
    city: "Hohenschwangau",
    region: "Germany",
    latitude: 47.5576,
    longitude: 10.7498,
    difficulty: 2,
    tags: ["castle", "alpine", "iconic"],
    attribution: "Wikimedia Commons. Wikipedia: Neuschwanstein Castle.",
    sourceUrl: "https://en.wikipedia.org/wiki/Neuschwanstein_Castle",
    sceneKind: "wikimedia",
    sceneUrl: commons("Neuschwanstein_Castle_LOC_print.jpg"),
  }),
  loc({
    id: "loc_118",
    country: "WORLD",
    nation: "CH",
    title: "Matterhorn",
    city: "Zermatt",
    region: "Switzerland",
    latitude: 45.9763,
    longitude: 7.6586,
    difficulty: 2,
    tags: ["mountain", "alpine", "iconic"],
    attribution: "Wikimedia Commons. Wikipedia: Matterhorn.",
    sourceUrl: "https://en.wikipedia.org/wiki/Matterhorn",
    sceneKind: "wikimedia",
    sceneUrl: commons("Matterhorn_from_Dom.jpg"),
  }),
  loc({
    id: "loc_119",
    country: "WORLD",
    nation: "IS",
    title: "Hallgrímskirkja",
    city: "Reykjavík",
    region: "Iceland",
    latitude: 64.1417,
    longitude: -21.9266,
    difficulty: 3,
    tags: ["church", "urban", "nordic"],
    attribution: "Wikimedia Commons. Wikipedia: Hallgrímskirkja.",
    sourceUrl: "https://en.wikipedia.org/wiki/Hallgr%C3%ADmskirkja",
    sceneKind: "wikimedia",
    sceneUrl: commons("Hallgrímskirkja.jpg"),
  }),
  loc({
    id: "loc_120",
    country: "WORLD",
    nation: "NO",
    title: "Tromsø",
    city: "Tromsø",
    region: "Norway",
    latitude: 69.6492,
    longitude: 18.9553,
    difficulty: 4,
    tags: ["arctic", "harbor", "nordic"],
    attribution: "Wikimedia Commons. Wikipedia: Tromsø.",
    sourceUrl: "https://en.wikipedia.org/wiki/Troms%C3%B8",
    sceneKind: "wikimedia",
    sceneUrl: commons("Tromso_bridge.jpg"),
  }),
  loc({
    id: "loc_121",
    country: "WORLD",
    nation: "SE",
    title: "Gamla Stan",
    city: "Stockholm",
    region: "Sweden",
    latitude: 59.325,
    longitude: 18.0708,
    difficulty: 3,
    tags: ["historic", "island", "urban"],
    attribution: "Wikimedia Commons. Wikipedia: Gamla stan.",
    sourceUrl: "https://en.wikipedia.org/wiki/Gamla_stan",
    sceneKind: "wikimedia",
    sceneUrl: commons("Stockholm_Gamla_Stan.jpg"),
  }),
  loc({
    id: "loc_122",
    country: "WORLD",
    nation: "FI",
    title: "Helsinki Cathedral",
    city: "Helsinki",
    region: "Finland",
    latitude: 60.1704,
    longitude: 24.9521,
    difficulty: 3,
    tags: ["church", "urban", "nordic"],
    attribution: "Wikimedia Commons. Wikipedia: Helsinki Cathedral.",
    sourceUrl: "https://en.wikipedia.org/wiki/Helsinki_Cathedral",
    sceneKind: "wikimedia",
    sceneUrl: commons("Helsinki_Cathedral_in_July_2004.jpg"),
  }),
  loc({
    id: "loc_123",
    country: "WORLD",
    nation: "HR",
    title: "Dubrovnik",
    city: "Dubrovnik",
    region: "Croatia",
    latitude: 42.6406,
    longitude: 18.1103,
    difficulty: 3,
    tags: ["walls", "coastal", "historic"],
    attribution: "Wikimedia Commons. Wikipedia: Dubrovnik.",
    sourceUrl: "https://en.wikipedia.org/wiki/Dubrovnik",
    sceneKind: "wikimedia",
    sceneUrl: commons("Dubrovnik_old_town.jpg"),
  }),
  loc({
    id: "loc_124",
    country: "WORLD",
    nation: "HU",
    title: "Hungarian Parliament",
    city: "Budapest",
    region: "Hungary",
    latitude: 47.507,
    longitude: 19.0456,
    difficulty: 2,
    tags: ["civic", "danube", "architecture"],
    attribution: "Wikimedia Commons. Wikipedia: Hungarian Parliament Building.",
    sourceUrl: "https://en.wikipedia.org/wiki/Hungarian_Parliament_Building",
    sceneKind: "wikimedia",
    sceneUrl: commons("Parliament_of_Hungary_September_2013.jpg"),
  }),
  loc({
    id: "loc_125",
    country: "WORLD",
    nation: "IE",
    title: "Ha'penny Bridge",
    city: "Dublin",
    region: "Ireland",
    latitude: 53.3463,
    longitude: -6.263,
    difficulty: 3,
    tags: ["bridge", "urban", "river"],
    attribution: "Wikimedia Commons. Wikipedia: Ha'penny Bridge.",
    sourceUrl: "https://en.wikipedia.org/wiki/Ha%27penny_Bridge",
    sceneKind: "wikimedia",
    sceneUrl: commons("Ha'penny_Bridge,_Dublin.jpg"),
  }),
  loc({
    id: "loc_126",
    country: "WORLD",
    nation: "GB",
    title: "Edinburgh Castle",
    city: "Edinburgh",
    region: "United Kingdom",
    latitude: 55.9486,
    longitude: -3.1999,
    difficulty: 2,
    tags: ["castle", "rock", "historic"],
    attribution: "Wikimedia Commons. Wikipedia: Edinburgh Castle.",
    sourceUrl: "https://en.wikipedia.org/wiki/Edinburgh_Castle",
    sceneKind: "wikimedia",
    sceneUrl: commons("Edinburgh_Castle_from_the_south_east.jpg"),
  }),
  loc({
    id: "loc_127",
    country: "WORLD",
    nation: "US",
    title: "Times Square",
    city: "New York",
    region: "United States",
    latitude: 40.758,
    longitude: -73.9855,
    difficulty: 2,
    tags: ["urban", "neon", "iconic"],
    attribution: "Wikimedia Commons. Wikipedia: Times Square.",
    sourceUrl: "https://en.wikipedia.org/wiki/Times_Square",
    sceneKind: "wikimedia",
    sceneUrl: commons("Times_Square_1.JPG"),
  }),
  loc({
    id: "loc_128",
    country: "WORLD",
    nation: "CA",
    title: "Lake Louise",
    city: "Banff",
    region: "Canada",
    latitude: 51.4254,
    longitude: -116.1773,
    difficulty: 3,
    tags: ["lake", "mountain", "park"],
    attribution: "Wikimedia Commons. Wikipedia: Lake Louise (Alberta).",
    sourceUrl: "https://en.wikipedia.org/wiki/Lake_Louise,_Alberta",
    sceneKind: "wikimedia",
    sceneUrl: commons("Moraine_Lake_17092005.jpg"),
  }),
  loc({
    id: "loc_129",
    country: "WORLD",
    nation: "MX",
    title: "Chichén Itzá",
    city: "Yucatán",
    region: "Mexico",
    latitude: 20.6843,
    longitude: -88.5678,
    difficulty: 2,
    tags: ["ruins", "pyramid", "iconic"],
    attribution: "Wikimedia Commons. Wikipedia: Chichen Itza.",
    sourceUrl: "https://en.wikipedia.org/wiki/Chichen_Itza",
    sceneKind: "wikimedia",
    sceneUrl: commons("Chichen_Itza_3.jpg"),
  }),
  loc({
    id: "loc_130",
    country: "WORLD",
    nation: "AR",
    title: "Iguazú Falls",
    city: "Misiones",
    region: "Argentina",
    latitude: -25.6953,
    longitude: -54.4367,
    difficulty: 3,
    tags: ["waterfall", "jungle", "iconic"],
    attribution: "Wikimedia Commons. Wikipedia: Iguazu Falls.",
    sourceUrl: "https://en.wikipedia.org/wiki/Iguazu_Falls",
    sceneKind: "wikimedia",
    sceneUrl: commons("Iguazu_Falls.jpg"),
  }),
  loc({
    id: "loc_131",
    country: "WORLD",
    nation: "CL",
    title: "Torres del Paine",
    city: "Magallanes",
    region: "Chile",
    latitude: -50.9423,
    longitude: -73.4068,
    difficulty: 3,
    tags: ["mountain", "patagonia", "park"],
    attribution: "Wikimedia Commons. Wikipedia: Torres del Paine National Park.",
    sourceUrl: "https://en.wikipedia.org/wiki/Torres_del_Paine_National_Park",
    sceneKind: "wikimedia",
    sceneUrl: commons("Cuernos_del_Paine_from_Lake_Pehoé.jpg"),
  }),
  loc({
    id: "loc_132",
    country: "WORLD",
    nation: "KH",
    title: "Angkor Wat",
    city: "Siem Reap",
    region: "Cambodia",
    latitude: 13.4125,
    longitude: 103.867,
    difficulty: 2,
    tags: ["temple", "ruins", "iconic"],
    attribution: "Wikimedia Commons. Wikipedia: Angkor Wat.",
    sourceUrl: "https://en.wikipedia.org/wiki/Angkor_Wat",
    sceneKind: "wikimedia",
    sceneUrl: commons("Angkor_Wat.jpg"),
  }),
  loc({
    id: "loc_133",
    country: "WORLD",
    nation: "VN",
    title: "Hạ Long Bay",
    city: "Quảng Ninh",
    region: "Vietnam",
    latitude: 20.9101,
    longitude: 107.1839,
    difficulty: 3,
    tags: ["bay", "karst", "boats"],
    attribution: "Wikimedia Commons. Wikipedia: Ha Long Bay.",
    sourceUrl: "https://en.wikipedia.org/wiki/Ha_Long_Bay",
    sceneKind: "wikimedia",
    sceneUrl: commons("Ha_Long_Bay_(33220311453).jpg"),
  }),
  loc({
    id: "loc_134",
    country: "WORLD",
    nation: "TH",
    title: "Wat Arun",
    city: "Bangkok",
    region: "Thailand",
    latitude: 13.7437,
    longitude: 100.4888,
    difficulty: 3,
    tags: ["temple", "river", "urban"],
    attribution: "Wikimedia Commons. Wikipedia: Wat Arun.",
    sourceUrl: "https://en.wikipedia.org/wiki/Wat_Arun",
    sceneKind: "wikimedia",
    sceneUrl: commons("Wat_Arun_Bangkok.jpg"),
  }),
  loc({
    id: "loc_135",
    country: "WORLD",
    nation: "ID",
    title: "Tanah Lot",
    city: "Bali",
    region: "Indonesia",
    latitude: -8.6212,
    longitude: 115.0868,
    difficulty: 3,
    tags: ["temple", "coastal", "island"],
    attribution: "Wikimedia Commons. Wikipedia: Tanah Lot.",
    sourceUrl: "https://en.wikipedia.org/wiki/Tanah_Lot",
    sceneKind: "wikimedia",
    sceneUrl: commons("TanahLot.jpg"),
  }),
  loc({
    id: "loc_136",
    country: "WORLD",
    nation: "KR",
    title: "Gyeongbokgung",
    city: "Seoul",
    region: "South Korea",
    latitude: 37.5796,
    longitude: 126.977,
    difficulty: 3,
    tags: ["palace", "urban", "historic"],
    attribution: "Wikimedia Commons. Wikipedia: Gyeongbokgung.",
    sourceUrl: "https://en.wikipedia.org/wiki/Gyeongbokgung",
    sceneKind: "wikimedia",
    sceneUrl: commons("Gyeongbokgung-Gwanghwamun-01.jpg"),
  }),
  loc({
    id: "loc_137",
    country: "WORLD",
    nation: "SG",
    title: "Marina Bay Sands",
    city: "Singapore",
    region: "Singapore",
    latitude: 1.2834,
    longitude: 103.8607,
    difficulty: 2,
    tags: ["iconic", "skyline", "harbor"],
    attribution: "Wikimedia Commons. Wikipedia: Marina Bay Sands.",
    sourceUrl: "https://en.wikipedia.org/wiki/Marina_Bay_Sands",
    sceneKind: "wikimedia",
    sceneUrl: commons("Marina_Bay_Sands_in_the_evening_-_20101120.jpg"),
  }),
  loc({
    id: "loc_138",
    country: "WORLD",
    nation: "HK",
    title: "Victoria Peak",
    city: "Hong Kong",
    region: "Hong Kong",
    latitude: 22.2759,
    longitude: 114.1455,
    difficulty: 3,
    tags: ["skyline", "mountain", "harbor"],
    attribution: "Wikimedia Commons. Wikipedia: Victoria Peak.",
    sourceUrl: "https://en.wikipedia.org/wiki/Victoria_Peak",
    sceneKind: "wikimedia",
    sceneUrl: commons("Hong_Kong_Night_Skyline.jpg"),
  }),
  loc({
    id: "loc_139",
    country: "WORLD",
    nation: "EG",
    title: "Giza Pyramids",
    city: "Giza",
    region: "Egypt",
    latitude: 29.9792,
    longitude: 31.1342,
    difficulty: 1,
    tags: ["pyramid", "desert", "iconic"],
    attribution: "Wikimedia Commons. Wikipedia: Giza pyramid complex.",
    sourceUrl: "https://en.wikipedia.org/wiki/Giza_pyramid_complex",
    sceneKind: "wikimedia",
    sceneUrl: commons("All_Gizah_Pyramids.jpg"),
  }),
  loc({
    id: "loc_140",
    country: "WORLD",
    nation: "MA",
    title: "Jemaa el-Fnaa",
    city: "Marrakesh",
    region: "Morocco",
    latitude: 31.6258,
    longitude: -7.9891,
    difficulty: 3,
    tags: ["square", "medina", "urban"],
    attribution: "Wikimedia Commons. Wikipedia: Jemaa el-Fnaa.",
    sourceUrl: "https://en.wikipedia.org/wiki/Jemaa_el-Fnaa",
    sceneKind: "wikimedia",
    sceneUrl: commons("Jamaa_El_Fna.jpg"),
  }),
  loc({
    id: "loc_141",
    country: "WORLD",
    nation: "TZ",
    title: "Serengeti",
    city: "Serengeti",
    region: "Tanzania",
    latitude: -2.3333,
    longitude: 34.8333,
    difficulty: 4,
    tags: ["savanna", "wildlife", "park"],
    attribution: "Wikimedia Commons. Wikipedia: Serengeti.",
    sourceUrl: "https://en.wikipedia.org/wiki/Serengeti",
    sceneKind: "wikimedia",
    sceneUrl: commons("Serengeti.jpg"),
  }),
  loc({
    id: "loc_142",
    country: "WORLD",
    nation: "ZM",
    title: "Victoria Falls",
    city: "Livingstone",
    region: "Zambia",
    latitude: -17.9243,
    longitude: 25.8572,
    difficulty: 3,
    tags: ["waterfall", "iconic", "river"],
    attribution: "Wikimedia Commons. Wikipedia: Victoria Falls.",
    sourceUrl: "https://en.wikipedia.org/wiki/Victoria_Falls",
    sceneKind: "wikimedia",
    sceneUrl: commons("Victoria_Falls.jpg"),
  }),
  loc({
    id: "loc_143",
    country: "WORLD",
    nation: "AU",
    title: "Uluru",
    city: "Northern Territory",
    region: "Australia",
    latitude: -25.3444,
    longitude: 131.0369,
    difficulty: 2,
    tags: ["rock", "desert", "iconic"],
    attribution: "Wikimedia Commons. Wikipedia: Uluru.",
    sourceUrl: "https://en.wikipedia.org/wiki/Uluru",
    sceneKind: "wikimedia",
    sceneUrl: commons("Uluru_Australia.jpg"),
  }),
  loc({
    id: "loc_144",
    country: "WORLD",
    nation: "NZ",
    title: "Milford Sound",
    city: "Fiordland",
    region: "New Zealand",
    latitude: -44.641,
    longitude: 167.896,
    difficulty: 3,
    tags: ["fjord", "mountain", "water"],
    attribution: "Wikimedia Commons. Wikipedia: Milford Sound.",
    sourceUrl: "https://en.wikipedia.org/wiki/Milford_Sound",
    sceneKind: "wikimedia",
    sceneUrl: commons("Milford_Sound_New_Zealand.jpg"),
  }),
  loc({
    id: "loc_145",
    country: "WORLD",
    nation: "TR",
    title: "Cappadocia",
    city: "Göreme",
    region: "Turkey",
    latitude: 38.6431,
    longitude: 34.8289,
    difficulty: 3,
    tags: ["rock", "valley", "balloons"],
    attribution: "Wikimedia Commons. Wikipedia: Cappadocia.",
    sourceUrl: "https://en.wikipedia.org/wiki/Cappadocia",
    sceneKind: "wikimedia",
    sceneUrl: commons("Cappadocia_Ballooning.jpg"),
  }),
  loc({
    id: "loc_146",
    country: "WORLD",
    nation: "TR",
    title: "Sultan Ahmed Mosque",
    city: "Istanbul",
    region: "Turkey",
    latitude: 41.0054,
    longitude: 28.9768,
    difficulty: 2,
    tags: ["mosque", "historic", "urban"],
    attribution: "Wikimedia Commons. Wikipedia: Blue Mosque, Istanbul.",
    sourceUrl: "https://en.wikipedia.org/wiki/Blue_Mosque,_Istanbul",
    sceneKind: "wikimedia",
    sceneUrl: commons("Sultan_Ahmed_Mosque_Istanbul.jpg"),
  }),
  loc({
    id: "loc_147",
    country: "WORLD",
    nation: "GR",
    title: "Acropolis",
    city: "Athens",
    region: "Greece",
    latitude: 37.9715,
    longitude: 23.7267,
    difficulty: 2,
    tags: ["ruins", "iconic", "hill"],
    attribution: "Wikimedia Commons. Wikipedia: Acropolis of Athens.",
    sourceUrl: "https://en.wikipedia.org/wiki/Acropolis_of_Athens",
    sceneKind: "wikimedia",
    sceneUrl: commons("Acropolis_of_Athens_from_Philopappos_Hill.jpg"),
  }),
  loc({
    id: "loc_148",
    country: "WORLD",
    nation: "IT",
    title: "Grand Canal",
    city: "Venice",
    region: "Italy",
    latitude: 45.4378,
    longitude: 12.3358,
    difficulty: 2,
    tags: ["canal", "urban", "iconic"],
    attribution: "Wikimedia Commons. Wikipedia: Grand Canal (Venice).",
    sourceUrl: "https://en.wikipedia.org/wiki/Grand_Canal_(Venice)",
    sceneKind: "wikimedia",
    sceneUrl: commons("Canal_Grande_Chiesa_della_Salute_e_Dogana_dal_ponte_dell_Accademia.jpg"),
  }),
  loc({
    id: "loc_149",
    country: "WORLD",
    nation: "US",
    title: "Grand Canyon",
    city: "Arizona",
    region: "United States",
    latitude: 36.0544,
    longitude: -112.1401,
    difficulty: 2,
    tags: ["canyon", "desert", "iconic"],
    attribution: "Wikimedia Commons. Wikipedia: Grand Canyon.",
    sourceUrl: "https://en.wikipedia.org/wiki/Grand_Canyon",
    sceneKind: "wikimedia",
    sceneUrl: commons("Grand_Canyon_Hopi_Point_2018.jpg"),
  }),
];
