// Generated by scripts/fetch-new-photos.mjs — do not edit by hand. A location
// in new-locations.ts is only playable once its photo is listed here.

export interface PhotoCredit {
  /** "Photo: <author>, Wikimedia Commons, <licence>." */
  attribution: string;
  /** The Commons file page. */
  source: string;
  /** Extra viewpoints saved as /locations/views/<id>-2.jpg, -3.jpg … */
  views: number;
}

export const NEW_PHOTOS: Record<string, PhotoCredit> = {};

/**
 * Existing places: extra viewpoints (and, for the softest old plates, a
 * sharper replacement photo). The attribution here replaces the place's own.
 */
export const PHOTO_EXTRAS: Record<string, Partial<PhotoCredit>> = {};
