/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DuelRouteImport } from './routes/duel'
import { Route as PlayRouteImport } from './routes/play'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as DuelIndexRouteImport } from './routes/duel.index'
import { Route as DuelCodeRouteImport } from './routes/duel.$code'
import { Route as DuelBotRouteImport } from './routes/duel.bot'
import { Route as DuelHotseatRouteImport } from './routes/duel.hotseat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelRoute = DuelRouteImport.update({
  id: '/duel',
  path: '/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelIndexRoute = DuelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DuelRoute,
} as any)
const DuelCodeRoute = DuelCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => DuelRoute,
} as any)
const DuelBotRoute = DuelBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => DuelRoute,
} as any)
const DuelHotseatRoute = DuelHotseatRouteImport.update({
  id: '/hotseat',
  path: '/hotseat',
  getParentRoute: () => DuelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/duel': typeof DuelRouteWithChildren
  '/play': typeof PlayRoute
  '/api/rtc': typeof ApiRtcRoute
  '/duel/$code': typeof DuelCodeRoute
  '/duel/bot': typeof DuelBotRoute
  '/duel/hotseat': typeof DuelHotseatRoute
  '/duel/': typeof DuelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play': typeof PlayRoute
  '/api/rtc': typeof ApiRtcRoute
  '/duel/$code': typeof DuelCodeRoute
  '/duel/bot': typeof DuelBotRoute
  '/duel/hotseat': typeof DuelHotseatRoute
  '/duel': typeof DuelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/duel': typeof DuelRouteWithChildren
  '/play': typeof PlayRoute
  '/api/rtc': typeof ApiRtcRoute
  '/duel/$code': typeof DuelCodeRoute
  '/duel/bot': typeof DuelBotRoute
  '/duel/hotseat': typeof DuelHotseatRoute
  '/duel/': typeof DuelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/duel'
    | '/play'
    | '/api/rtc'
    | '/duel/$code'
    | '/duel/bot'
    | '/duel/hotseat'
    | '/duel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/play'
    | '/api/rtc'
    | '/duel/$code'
    | '/duel/bot'
    | '/duel/hotseat'
    | '/duel'
  id:
    | '__root__'
    | '/'
    | '/duel'
    | '/play'
    | '/api/rtc'
    | '/duel/$code'
    | '/duel/bot'
    | '/duel/hotseat'
    | '/duel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DuelRoute: typeof DuelRouteWithChildren
  PlayRoute: typeof PlayRoute
  ApiRtcRoute: typeof ApiRtcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel': {
      id: '/duel'
      path: '/duel'
      fullPath: '/duel'
      preLoaderRoute: typeof DuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel/': {
      id: '/duel/'
      path: '/'
      fullPath: '/duel/'
      preLoaderRoute: typeof DuelIndexRouteImport
      parentRoute: typeof DuelRoute
    }
    '/duel/$code': {
      id: '/duel/$code'
      path: '/$code'
      fullPath: '/duel/$code'
      preLoaderRoute: typeof DuelCodeRouteImport
      parentRoute: typeof DuelRoute
    }
    '/duel/bot': {
      id: '/duel/bot'
      path: '/bot'
      fullPath: '/duel/bot'
      preLoaderRoute: typeof DuelBotRouteImport
      parentRoute: typeof DuelRoute
    }
    '/duel/hotseat': {
      id: '/duel/hotseat'
      path: '/hotseat'
      fullPath: '/duel/hotseat'
      preLoaderRoute: typeof DuelHotseatRouteImport
      parentRoute: typeof DuelRoute
    }
  }
}

interface DuelRouteChildren {
  DuelCodeRoute: typeof DuelCodeRoute
  DuelBotRoute: typeof DuelBotRoute
  DuelHotseatRoute: typeof DuelHotseatRoute
  DuelIndexRoute: typeof DuelIndexRoute
}

const DuelRouteChildren: DuelRouteChildren = {
  DuelCodeRoute: DuelCodeRoute,
  DuelBotRoute: DuelBotRoute,
  DuelHotseatRoute: DuelHotseatRoute,
  DuelIndexRoute: DuelIndexRoute,
}

const DuelRouteWithChildren = DuelRoute._addFileChildren(DuelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DuelRoute: DuelRouteWithChildren,
  PlayRoute: PlayRoute,
  ApiRtcRoute: ApiRtcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
